from enum import Enum


class AllowanceCategory(Enum):
    NONDEDUCTIBLE = "NONDEDUCTIBLE"
    UNIFORM = "UNIFORM"
    PRIVATEVEHICLE = "PRIVATEVEHICLE"
    HOMEOFFICE = "HOMEOFFICE"
    TRANSPORT = "TRANSPORT"
    GENERAL = "GENERAL"
    OTHER = "OTHER"
