from enum import Enum


class EarningsType(Enum):
    FIXED = "FIXED"
    ORDINARYTIMEEARNINGS = "ORDINARYTIMEEARNINGS"
    OVERTIMEEARNINGS = "OVERTIMEEARNINGS"
    ALLOWANCE = "ALLOWANCE"
    LUMPSUMD = "LUMPSUMD"
    EMPLOYMENTTERMINATIONPAYMENT = "EMPLOYMENTTERMINATIONPAYMENT"
    LUMPSUMA = "LUMPSUMA"
    LUMPSUMB = "LUMPSUMB"
    BONUSESANDCOMMISSIONS = "BONUSESANDCOMMISSIONS"
    LUMPSUME = "LUMPSUME"
    LUMPSUMW = "LUMPSUMW"
    DIRECTORSFEES = "DIRECTORSFEES"
    PAIDPARENTALLEAVE = "PAIDPARENTALLEAVE"
    WORKERSCOMPENSATION = "WORKERSCOMPENSATION"
