from enum import Enum


class EmploymentBasis(Enum):
    FULLTIME = "FULLTIME"
    PARTTIME = "PARTTIME"
    CASUAL = "CASUAL"
    LABOURHIRE = "LABOURHIRE"
    SUPERINCOMESTREAM = "SUPERINCOMESTREAM"
    NONEMPLOYEE = "NONEMPLOYEE"
