from enum import Enum


class IncomeType(Enum):
    SALARYANDWAGES = "SALARYANDWAGES"
    WORKINGHOLIDAYMAKER = "WORKINGHOLIDAYMAKER"
    NONEMPLOYEE = "NONEMPLOYEE"
    CLOSELYHELDPAYEES = "CLOSELYHELDPAYEES"
    LABOURHIRE = "LABOURHIRE"
