from enum import Enum


class LeaveCategoryCode(Enum):
    ANNUALLEAVE = "ANNUALLEAVE"
    LONGSERVICELEAVE = "LONGSERVICELEAVE"
    PERSONALSICKCARERSLEAVE = "PERSONALSICKCARERSLEAVE"
    ROSTEREDDAYOFF = "ROSTEREDDAYOFF"
    TIMEOFFINLIEU = "TIMEOFFINLIEU"
    COMPASSIONATEANDBEREAVEMENTLEAVE = "COMPASSIONATEANDBEREAVEMENTLEAVE"
    STUDYLEAVE = "STUDYLEAVE"
    FAMILYANDDOMESTICVIOLENCELEAVE = "FAMILYANDDOMESTICVIOLENCELEAVE"
    SPECIALPAIDLEAVE = "SPECIALPAIDLEAVE"
    COMMUNITYSERVICELEAVE = "COMMUNITYSERVICELEAVE"
    JURYDUTYLEAVE = "JURYDUTYLEAVE"
    DEFENCERESERVELEAVE = "DEFENCERESERVELEAVE"
