from enum import Enum


class LeaveLineCalculationType(Enum):
    NOCALCULATIONREQUIRED = "NOCALCULATIONREQUIRED"
    FIXEDAMOUNTEACHPERIOD = "FIXEDAMOUNTEACHPERIOD"
    ENTERRATEINPAYTEMPLATE = "ENTERRATEINPAYTEMPLATE"
    BASEDONORDINARYEARNINGS = "BASEDONORDINARYEARNINGS"
