from enum import Enum


class ManualTaxType(Enum):
    PAYGMANUAL = "PAYGMANUAL"
    ETPOMANUAL = "ETPOMANUAL"
    ETPRMANUAL = "ETPRMANUAL"
    SCHEDULE5MANUAL = "SCHEDULE5MANUAL"
    SCHEDULE5STSLMANUAL = "SCHEDULE5STSLMANUAL"
    SCHEDULE4MANUAL = "SCHEDULE4MANUAL"
