from enum import Enum


class PaymentFrequencyType(Enum):
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    FORTNIGHTLY = "FORTNIGHTLY"
    QUARTERLY = "QUARTERLY"
    TWICEMONTHLY = "TWICEMONTHLY"
    FOURWEEKLY = "FOURWEEKLY"
    YEARLY = "YEARLY"
