from enum import Enum


class TaxScaleType(Enum):
    REGULAR = "REGULAR"
    ACTORSARTISTSENTERTAINERS = "ACTORSARTISTSENTERTAINERS"
    HORTICULTURISTORSHEARER = "HORTICULTURISTORSHEARER"
    SENIORORPENSIONER = "SENIORORPENSIONER"
    WORKINGHOLIDAYMAKER = "WORKINGHOLIDAYMAKER"
    FOREIGN = "FOREIGN"
