# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.user1 import User1  # noqa: E501


class TestUser1(unittest.TestCase):
    """User1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User1:
        """Test User1
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `User1`
        """
        model = User1()  # noqa: E501
        if include_optional:
            return User1(
                id = '4ff1e5cc-9835-40d5-bb18-09fdb118db9c',
                name = 'john.smith@mail.com',
                first_name = 'John',
                last_name = 'Smith',
                full_name = 'Smith'
            )
        else:
            return User1(
                id = '4ff1e5cc-9835-40d5-bb18-09fdb118db9c',
        )
        """

    def testUser1(self):
        """Test User1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
