# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.super_funds import SuperFunds  # noqa: E501


class TestSuperFunds(unittest.TestCase):
    """SuperFunds unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuperFunds:
        """Test SuperFunds
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SuperFunds`
        """
        model = SuperFunds()  # noqa: E501
        if include_optional:
            return SuperFunds(
                super_funds = [
                    xero_python.models.super_fund.SuperFund(
                        super_fund_id = 'bfac31bd-ea62-4fc8-a5e7-7965d9504b15', 
                        type = 'REGULATED', 
                        name = 'MLC Navigator Retirement Plan - Superannuation Service (including Series 2) (MLC Superannuation Fund)', 
                        abn = '40022701955', 
                        bsb = '234324', 
                        account_number = '234234234', 
                        account_name = 'Money account', 
                        electronic_service_address = '12345678', 
                        employer_number = '324324', 
                        spin = '4545445454', 
                        usi = '40022701955001', 
                        updated_date_utc = '/Date(1583967733054+0000)/', 
                        validation_errors = [
                            xero_python.models.validation_error.ValidationError(
                                message = '', )
                            ], )
                    ]
            )
        else:
            return SuperFunds(
        )
        """

    def testSuperFunds(self):
        """Test SuperFunds"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
