# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.employee_leave_type import EmployeeLeaveType  # noqa: E501


class TestEmployeeLeaveType(unittest.TestCase):
    """EmployeeLeaveType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmployeeLeaveType:
        """Test EmployeeLeaveType
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EmployeeLeaveType`
        """
        model = EmployeeLeaveType()  # noqa: E501
        if include_optional:
            return EmployeeLeaveType(
                leave_type_id = '',
                schedule_of_accrual = 'BeginningOfCalendarYear',
                hours_accrued_annually = 1.337,
                maximum_to_accrue = 1.337,
                opening_balance = 1.337,
                rate_accrued_hourly = 1.337,
                schedule_of_accrual_date = 'Mon Apr 01 01:00:00 BST 2024'
            )
        else:
            return EmployeeLeaveType(
                leave_type_id = '',
                schedule_of_accrual = 'BeginningOfCalendarYear',
        )
        """

    def testEmployeeLeaveType(self):
        """Test EmployeeLeaveType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
