# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.statutory_deduction_object import StatutoryDeductionObject  # noqa: E501


class TestStatutoryDeductionObject(unittest.TestCase):
    """StatutoryDeductionObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatutoryDeductionObject:
        """Test StatutoryDeductionObject
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `StatutoryDeductionObject`
        """
        model = StatutoryDeductionObject()  # noqa: E501
        if include_optional:
            return StatutoryDeductionObject(
                pagination = xero_python.models.pagination.Pagination(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                problem = xero_python.models.problem.Problem(
                    type = 'application/problem+json', 
                    title = 'BadRequest', 
                    status = '400', 
                    detail = 'Validation error occurred.', 
                    instance = '', 
                    invalid_fields = [
                        xero_python.models.invalid_field.InvalidField(
                            name = 'DateOfBirth', 
                            reason = 'The Date of Birth is required.', )
                        ], ),
                statutory_deduction = xero_python.models.statutory_deduction.StatutoryDeduction(
                    id = '', 
                    name = '', 
                    statutory_deduction_category = 'PriorityOrder', 
                    liability_account_id = '', 
                    current_record = True, )
            )
        else:
            return StatutoryDeductionObject(
        )
        """

    def testStatutoryDeductionObject(self):
        """Test StatutoryDeductionObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
