# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.payments import Payments  # noqa: E501


class TestPayments(unittest.TestCase):
    """Payments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Payments:
        """Test Payments
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Payments`
        """
        model = Payments()  # noqa: E501
        if include_optional:
            return Payments(
                pagination = xero_python.models.pagination_1.Pagination_1(
                    page = 56, 
                    page_size = 56, 
                    page_count = 56, 
                    item_count = 56, ),
                warnings = [
                    xero_python.models.validation_error.ValidationError(
                        message = '', )
                    ],
                payments = [
                    xero_python.models.payment.Payment(
                        invoice = xero_python.models.invoice.Invoice(
                            type = 'ACCPAY', 
                            contact = xero_python.models.contact.Contact(
                                contact_id = '', 
                                merged_to_contact_id = '', 
                                contact_number = '', 
                                account_number = '', 
                                contact_status = 'ACTIVE', 
                                name = '', 
                                first_name = '', 
                                last_name = '', 
                                company_number = '', 
                                email_address = '', 
                                contact_persons = [
                                    xero_python.models.contact_person.ContactPerson(
                                        first_name = '', 
                                        last_name = '', 
                                        email_address = '', 
                                        include_in_emails = True, )
                                    ], 
                                bank_account_details = '', 
                                tax_number = '', 
                                accounts_receivable_tax_type = '', 
                                accounts_payable_tax_type = '', 
                                addresses = [
                                    xero_python.models.address.Address(
                                        address_type = 'POBOX', 
                                        address_line1 = '', 
                                        address_line2 = '', 
                                        address_line3 = '', 
                                        address_line4 = '', 
                                        city = '', 
                                        region = '', 
                                        postal_code = '', 
                                        country = '', 
                                        attention_to = '', )
                                    ], 
                                phones = [
                                    xero_python.models.phone.Phone(
                                        phone_type = 'DEFAULT', 
                                        phone_number = '', 
                                        phone_area_code = '', 
                                        phone_country_code = '', )
                                    ], 
                                is_supplier = True, 
                                is_customer = True, 
                                sales_default_line_amount_type = 'INCLUSIVE', 
                                purchases_default_line_amount_type = 'INCLUSIVE', 
                                default_currency = 'AED', 
                                xero_network_key = '', 
                                sales_default_account_code = '', 
                                purchases_default_account_code = '', 
                                sales_tracking_categories = [
                                    xero_python.models.sales_tracking_category.SalesTrackingCategory(
                                        tracking_category_name = '', 
                                        tracking_option_name = '', )
                                    ], 
                                purchases_tracking_categories = [
                                    xero_python.models.sales_tracking_category.SalesTrackingCategory(
                                        tracking_category_name = '', 
                                        tracking_option_name = '', )
                                    ], 
                                tracking_category_name = '', 
                                tracking_category_option = '', 
                                payment_terms = xero_python.models.payment_term.PaymentTerm(
                                    bills = xero_python.models.bill.Bill(
                                        day = 56, 
                                        type = 'DAYSAFTERBILLDATE', ), 
                                    sales = xero_python.models.bill.Bill(
                                        day = 56, ), ), 
                                updated_date_utc = '/Date(1573755038314)/', 
                                contact_groups = [
                                    xero_python.models.contact_group.ContactGroup(
                                        name = '', 
                                        status = 'ACTIVE', 
                                        contact_group_id = '', 
                                        contacts = [
                                            xero_python.models.contact.Contact(
                                                contact_id = '', 
                                                merged_to_contact_id = '', 
                                                contact_number = '', 
                                                account_number = '', 
                                                contact_status = 'ACTIVE', 
                                                name = '', 
                                                first_name = '', 
                                                last_name = '', 
                                                company_number = '', 
                                                email_address = '', 
                                                bank_account_details = '', 
                                                tax_number = '', 
                                                accounts_receivable_tax_type = '', 
                                                accounts_payable_tax_type = '', 
                                                is_supplier = True, 
                                                is_customer = True, 
                                                sales_default_line_amount_type = 'INCLUSIVE', 
                                                purchases_default_line_amount_type = 'INCLUSIVE', 
                                                xero_network_key = '', 
                                                sales_default_account_code = '', 
                                                purchases_default_account_code = '', 
                                                tracking_category_name = '', 
                                                tracking_category_option = '', 
                                                updated_date_utc = '/Date(1573755038314)/', 
                                                website = '', 
                                                branding_theme = xero_python.models.branding_theme.BrandingTheme(
                                                    branding_theme_id = '', 
                                                    name = '', 
                                                    logo_url = '', 
                                                    sort_order = 56, 
                                                    created_date_utc = '/Date(1573755038314)/', ), 
                                                batch_payments = xero_python.models.batch_payment_details.BatchPaymentDetails(
                                                    bank_account_number = '123-456-1111111', 
                                                    bank_account_name = 'ACME Bank', 
                                                    details = 'Hello World', 
                                                    code = 'ABC', 
                                                    reference = 'Foobar', ), 
                                                discount = 1.337, 
                                                balances = xero_python.models.balances.Balances(
                                                    accounts_receivable = xero_python.models.accounts_receivable.AccountsReceivable(
                                                        outstanding = 1.337, 
                                                        overdue = 1.337, ), 
                                                    accounts_payable = xero_python.models.accounts_payable.AccountsPayable(
                                                        outstanding = 1.337, 
                                                        overdue = 1.337, ), ), 
                                                attachments = [
                                                    xero_python.models.attachment.Attachment(
                                                        attachment_id = '00000000-0000-0000-0000-000000000000', 
                                                        file_name = 'xero-dev.jpg', 
                                                        url = 'https://api.xero.com/api.xro/2.0/Accounts/da962997-a8bd-4dff-9616-01cdc199283f/Attachments/sample5.jpg', 
                                                        mime_type = 'image/jpg', 
                                                        content_length = 56, 
                                                        include_online = True, )
                                                    ], 
                                                has_attachments = False, 
                                                validation_errors = [
                                                    xero_python.models.validation_error.ValidationError(
                                                        message = '', )
                                                    ], 
                                                has_validation_errors = False, 
                                                status_attribute_string = '', )
                                            ], )
                                    ], 
                                website = '', 
                                branding_theme = xero_python.models.branding_theme.BrandingTheme(
                                    branding_theme_id = '', 
                                    name = '', 
                                    logo_url = '', 
                                    sort_order = 56, 
                                    created_date_utc = '/Date(1573755038314)/', ), 
                                batch_payments = xero_python.models.batch_payment_details.BatchPaymentDetails(
                                    bank_account_number = '123-456-1111111', 
                                    bank_account_name = 'ACME Bank', 
                                    details = 'Hello World', 
                                    code = 'ABC', 
                                    reference = 'Foobar', ), 
                                discount = 1.337, 
                                balances = xero_python.models.balances.Balances(), 
                                attachments = [
                                    xero_python.models.attachment.Attachment(
                                        attachment_id = '00000000-0000-0000-0000-000000000000', 
                                        file_name = 'xero-dev.jpg', 
                                        url = 'https://api.xero.com/api.xro/2.0/Accounts/da962997-a8bd-4dff-9616-01cdc199283f/Attachments/sample5.jpg', 
                                        mime_type = 'image/jpg', 
                                        content_length = 56, 
                                        include_online = True, )
                                    ], 
                                has_attachments = False, 
                                validation_errors = [
                                    xero_python.models.validation_error.ValidationError(
                                        message = '', )
                                    ], 
                                has_validation_errors = False, 
                                status_attribute_string = '', ), 
                            line_items = [
                                xero_python.models.line_item.LineItem(
                                    line_item_id = '00000000-0000-0000-0000-000000000000', 
                                    description = '', 
                                    quantity = 1.337, 
                                    unit_amount = 1.337, 
                                    item_code = '', 
                                    account_code = '', 
                                    account_id = '00000000-0000-0000-0000-000000000000', 
                                    tax_type = '', 
                                    tax_amount = 1.337, 
                                    item = xero_python.models.line_item_item.LineItemItem(
                                        code = '', 
                                        name = '', 
                                        item_id = '', ), 
                                    line_amount = 1.337, 
                                    tracking = [
                                        xero_python.models.line_item_tracking.LineItemTracking(
                                            tracking_category_id = '00000000-0000-0000-0000-000000000000', 
                                            tracking_option_id = '00000000-0000-0000-0000-000000000000', 
                                            name = 'Region', 
                                            option = 'North', )
                                        ], 
                                    discount_rate = 1.337, 
                                    discount_amount = 1.337, 
                                    repeating_invoice_id = '00000000-0000-0000-0000-000000000000', 
                                    taxability = 'TAXABLE', 
                                    sales_tax_code_id = 1.337, 
                                    tax_breakdown = [
                                        xero_python.models.tax_breakdown_component.TaxBreakdownComponent(
                                            tax_component_id = '', 
                                            name = '', 
                                            tax_percentage = 1.337, 
                                            tax_amount = 1.337, 
                                            taxable_amount = 1.337, 
                                            non_taxable_amount = 1.337, 
                                            exempt_amount = 1.337, 
                                            state_assigned_no = '', 
                                            jurisdiction_region = '', )
                                        ], )
                                ], 
                            date = '', 
                            due_date = '', 
                            line_amount_types = 'Exclusive', 
                            invoice_number = '', 
                            reference = '', 
                            branding_theme_id = '', 
                            url = '', 
                            currency_code = 'AED', 
                            currency_rate = 1.337, 
                            status = 'DRAFT', 
                            sent_to_contact = True, 
                            expected_payment_date = '', 
                            planned_payment_date = '', 
                            cis_deduction = 1.337, 
                            cis_rate = 1.337, 
                            sub_total = 1.337, 
                            total_tax = 1.337, 
                            total = 1.337, 
                            total_discount = 1.337, 
                            invoice_id = '', 
                            repeating_invoice_id = '', 
                            has_attachments = False, 
                            is_discounted = True, 
                            payments = [
                                xero_python.models.payment.Payment(
                                    credit_note = xero_python.models.credit_note.CreditNote(
                                        date = '', 
                                        due_date = '', 
                                        status = 'DRAFT', 
                                        sub_total = 1.337, 
                                        total_tax = 1.337, 
                                        total = 1.337, 
                                        cis_deduction = 1.337, 
                                        cis_rate = 1.337, 
                                        updated_date_utc = '/Date(1573755038314)/', 
                                        fully_paid_on_date = '', 
                                        credit_note_id = '', 
                                        credit_note_number = '', 
                                        reference = '', 
                                        sent_to_contact = True, 
                                        currency_rate = 1.337, 
                                        remaining_credit = 1.337, 
                                        allocations = [
                                            xero_python.models.allocation.Allocation(
                                                allocation_id = '', 
                                                invoice = xero_python.models.invoice.Invoice(
                                                    date = '', 
                                                    due_date = '', 
                                                    invoice_number = '', 
                                                    reference = '', 
                                                    branding_theme_id = '', 
                                                    url = '', 
                                                    currency_rate = 1.337, 
                                                    status = 'DRAFT', 
                                                    sent_to_contact = True, 
                                                    expected_payment_date = '', 
                                                    planned_payment_date = '', 
                                                    cis_deduction = 1.337, 
                                                    cis_rate = 1.337, 
                                                    sub_total = 1.337, 
                                                    total_tax = 1.337, 
                                                    total = 1.337, 
                                                    total_discount = 1.337, 
                                                    invoice_id = '', 
                                                    repeating_invoice_id = '', 
                                                    has_attachments = False, 
                                                    is_discounted = True, 
                                                    prepayments = [
                                                        xero_python.models.prepayment.Prepayment(
                                                            date = '', 
                                                            status = 'AUTHORISED', 
                                                            sub_total = 1.337, 
                                                            total_tax = 1.337, 
                                                            total = 1.337, 
                                                            reference = '', 
                                                            updated_date_utc = '/Date(1573755038314)/', 
                                                            prepayment_id = '', 
                                                            currency_rate = 1.337, 
                                                            remaining_credit = 1.337, 
                                                            applied_amount = 2.0, 
                                                            has_attachments = False, )
                                                        ], 
                                                    overpayments = [
                                                        xero_python.models.overpayment.Overpayment(
                                                            date = '', 
                                                            status = 'AUTHORISED', 
                                                            sub_total = 1.337, 
                                                            total_tax = 1.337, 
                                                            total = 1.337, 
                                                            updated_date_utc = '/Date(1573755038314)/', 
                                                            overpayment_id = '', 
                                                            currency_rate = 1.337, 
                                                            remaining_credit = 1.337, 
                                                            applied_amount = 2.0, 
                                                            has_attachments = False, )
                                                        ], 
                                                    amount_due = 1.337, 
                                                    amount_paid = 1.337, 
                                                    fully_paid_on_date = '', 
                                                    amount_credited = 1.337, 
                                                    updated_date_utc = '/Date(1573755038314)/', 
                                                    credit_notes = [
                                                        xero_python.models.credit_note.CreditNote(
                                                            date = '', 
                                                            due_date = '', 
                                                            status = 'DRAFT', 
                                                            sub_total = 1.337, 
                                                            total_tax = 1.337, 
                                                            total = 1.337, 
                                                            cis_deduction = 1.337, 
                                                            cis_rate = 1.337, 
                                                            updated_date_utc = '/Date(1573755038314)/', 
                                                            fully_paid_on_date = '', 
                                                            credit_note_id = '', 
                                                            credit_note_number = '', 
                                                            reference = '', 
                                                            sent_to_contact = True, 
                                                            currency_rate = 1.337, 
                                                            remaining_credit = 1.337, 
                                                            applied_amount = 2.0, 
                                                            branding_theme_id = '', 
                                                            status_attribute_string = '', 
                                                            has_attachments = False, 
                                                            has_errors = False, 
                                                            warnings = [
                                                                
                                                                ], 
                                                            invoice_addresses = [
                                                                xero_python.models.invoice_address.InvoiceAddress(
                                                                    invoice_address_type = 'FROM', 
                                                                    address_line1 = '', 
                                                                    address_line2 = '', 
                                                                    address_line3 = '', 
                                                                    address_line4 = '', 
                                                                    city = '', 
                                                                    region = '', 
                                                                    postal_code = '', 
                                                                    country = '', )
                                                                ], )
                                                        ], 
                                                    has_errors = False, 
                                                    status_attribute_string = '', 
                                                    warnings = [
                                                        
                                                        ], 
                                                    invoice_addresses = [
                                                        xero_python.models.invoice_address.InvoiceAddress(
                                                            invoice_address_type = 'FROM', 
                                                            address_line1 = '', 
                                                            address_line2 = '', 
                                                            address_line3 = '', 
                                                            address_line4 = '', 
                                                            city = '', 
                                                            region = '', 
                                                            postal_code = '', 
                                                            country = '', )
                                                        ], ), 
                                                overpayment = xero_python.models.overpayment.Overpayment(
                                                    date = '', 
                                                    status = 'AUTHORISED', 
                                                    sub_total = 1.337, 
                                                    total_tax = 1.337, 
                                                    total = 1.337, 
                                                    updated_date_utc = '/Date(1573755038314)/', 
                                                    overpayment_id = '', 
                                                    currency_rate = 1.337, 
                                                    remaining_credit = 1.337, 
                                                    applied_amount = 2.0, 
                                                    has_attachments = False, ), 
                                                prepayment = xero_python.models.prepayment.Prepayment(
                                                    date = '', 
                                                    status = 'AUTHORISED', 
                                                    sub_total = 1.337, 
                                                    total_tax = 1.337, 
                                                    total = 1.337, 
                                                    reference = '', 
                                                    updated_date_utc = '/Date(1573755038314)/', 
                                                    prepayment_id = '', 
                                                    currency_rate = 1.337, 
                                                    remaining_credit = 1.337, 
                                                    applied_amount = 2.0, 
                                                    has_attachments = False, ), 
                                                amount = 1.337, 
                                                date = '', 
                                                is_deleted = True, 
                                                status_attribute_string = '', )
                                            ], 
                                        applied_amount = 2.0, 
                                        branding_theme_id = '', 
                                        status_attribute_string = '', 
                                        has_attachments = False, 
                                        has_errors = False, 
                                        warnings = , 
                                        invoice_addresses = , ), 
                                    prepayment = , 
                                    overpayment = , 
                                    invoice_number = '', 
                                    credit_note_number = '', 
                                    batch_payment = xero_python.models.batch_payment.BatchPayment(
                                        account = xero_python.models.account.Account(
                                            code = '4400', 
                                            name = 'Food Sales', 
                                            account_id = '00000000-0000-0000-0000-000000000000', 
                                            bank_account_number = '', 
                                            status = 'ACTIVE', 
                                            description = '', 
                                            bank_account_type = 'BANK', 
                                            tax_type = '', 
                                            enable_payments_to_account = True, 
                                            show_in_expense_claims = True, 
                                            class = 'ASSET', 
                                            system_account = 'DEBTORS', 
                                            reporting_code = '', 
                                            reporting_code_name = '', 
                                            has_attachments = False, 
                                            updated_date_utc = '/Date(1573755038314)/', 
                                            add_to_watchlist = True, ), 
                                        reference = '', 
                                        particulars = '', 
                                        code = '', 
                                        details = '', 
                                        narrative = '', 
                                        batch_payment_id = '', 
                                        date_string = '', 
                                        date = '', 
                                        amount = 1.337, 
                                        status = 'AUTHORISED', 
                                        total_amount = 1.337, 
                                        updated_date_utc = '/Date(1573755038314)/', 
                                        is_reconciled = True, ), 
                                    account = xero_python.models.account.Account(
                                        code = '4400', 
                                        name = 'Food Sales', 
                                        account_id = '00000000-0000-0000-0000-000000000000', 
                                        bank_account_number = '', 
                                        status = 'ACTIVE', 
                                        description = '', 
                                        bank_account_type = 'BANK', 
                                        tax_type = '', 
                                        enable_payments_to_account = True, 
                                        show_in_expense_claims = True, 
                                        class = 'ASSET', 
                                        system_account = 'DEBTORS', 
                                        reporting_code = '', 
                                        reporting_code_name = '', 
                                        has_attachments = False, 
                                        updated_date_utc = '/Date(1573755038314)/', 
                                        add_to_watchlist = True, ), 
                                    code = '', 
                                    date = '', 
                                    currency_rate = 1.337, 
                                    amount = 1.337, 
                                    bank_amount = 1.337, 
                                    reference = '', 
                                    is_reconciled = True, 
                                    status = 'AUTHORISED', 
                                    payment_type = 'ACCRECPAYMENT', 
                                    updated_date_utc = '/Date(1573755038314)/', 
                                    payment_id = '00000000-0000-0000-0000-000000000000', 
                                    batch_payment_id = '00000000-0000-0000-0000-000000000000', 
                                    bank_account_number = '', 
                                    particulars = '', 
                                    details = '', 
                                    has_account = False, 
                                    has_validation_errors = False, 
                                    status_attribute_string = '', 
                                    warnings = , )
                                ], 
                            prepayments = [
                                
                                ], 
                            overpayments = [
                                
                                ], 
                            amount_due = 1.337, 
                            amount_paid = 1.337, 
                            fully_paid_on_date = '', 
                            amount_credited = 1.337, 
                            updated_date_utc = '/Date(1573755038314)/', 
                            credit_notes = [
                                
                                ], 
                            attachments = , 
                            has_errors = False, 
                            status_attribute_string = '', 
                            validation_errors = [
                                
                                ], 
                            warnings = , 
                            invoice_addresses = , ), 
                        credit_note = , 
                        prepayment = , 
                        overpayment = , 
                        invoice_number = '', 
                        credit_note_number = '', 
                        batch_payment = xero_python.models.batch_payment.BatchPayment(
                            reference = '', 
                            particulars = '', 
                            code = '', 
                            details = '', 
                            narrative = '', 
                            batch_payment_id = '', 
                            date_string = '', 
                            date = '', 
                            amount = 1.337, 
                            status = 'AUTHORISED', 
                            total_amount = 1.337, 
                            updated_date_utc = '/Date(1573755038314)/', 
                            is_reconciled = True, ), 
                        account = , 
                        code = '', 
                        date = '', 
                        currency_rate = 1.337, 
                        amount = 1.337, 
                        bank_amount = 1.337, 
                        reference = '', 
                        is_reconciled = True, 
                        status = 'AUTHORISED', 
                        payment_type = 'ACCRECPAYMENT', 
                        updated_date_utc = '/Date(1573755038314)/', 
                        payment_id = '00000000-0000-0000-0000-000000000000', 
                        batch_payment_id = '00000000-0000-0000-0000-000000000000', 
                        bank_account_number = '', 
                        particulars = '', 
                        details = '', 
                        has_account = False, 
                        has_validation_errors = False, 
                        status_attribute_string = '', 
                        validation_errors = [
                            
                            ], 
                        warnings = , )
                    ]
            )
        else:
            return Payments(
        )
        """

    def testPayments(self):
        """Test Payments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
