# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.working_week import WorkingWeek  # noqa: E501


class TestWorkingWeek(unittest.TestCase):
    """WorkingWeek unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkingWeek:
        """Test WorkingWeek
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkingWeek`
        """
        model = WorkingWeek()  # noqa: E501
        if include_optional:
            return WorkingWeek(
                monday = 1.337,
                tuesday = 1.337,
                wednesday = 1.337,
                thursday = 1.337,
                friday = 1.337,
                saturday = 1.337,
                sunday = 1.337
            )
        else:
            return WorkingWeek(
                monday = 1.337,
                tuesday = 1.337,
                wednesday = 1.337,
                thursday = 1.337,
                friday = 1.337,
                saturday = 1.337,
                sunday = 1.337,
        )
        """

    def testWorkingWeek(self):
        """Test WorkingWeek"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
