# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.error1 import Error1  # noqa: E501


class TestError1(unittest.TestCase):
    """Error1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Error1:
        """Test Error1
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Error1`
        """
        model = Error1()  # noqa: E501
        if include_optional:
            return Error1(
                message = '',
                model_state = None
            )
        else:
            return Error1(
        )
        """

    def testError1(self):
        """Test Error1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
