# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.pagination1 import Pagination1  # noqa: E501


class TestPagination1(unittest.TestCase):
    """Pagination1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Pagination1:
        """Test Pagination1
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Pagination1`
        """
        model = Pagination1()  # noqa: E501
        if include_optional:
            return Pagination1(
                page = 56,
                page_size = 56,
                page_count = 56,
                item_count = 56
            )
        else:
            return Pagination1(
        )
        """

    def testPagination1(self):
        """Test Pagination1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
