# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.trial_balance_movement import TrialBalanceMovement  # noqa: E501


class TestTrialBalanceMovement(unittest.TestCase):
    """TrialBalanceMovement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrialBalanceMovement:
        """Test TrialBalanceMovement
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TrialBalanceMovement`
        """
        model = TrialBalanceMovement()  # noqa: E501
        if include_optional:
            return TrialBalanceMovement(
                debits = 1.337,
                credits = 1.337,
                movement = xero_python.models.trial_balance_entry.TrialBalanceEntry(
                    value = 1.337, 
                    entry_type = '', ),
                signed_movement = 1.337
            )
        else:
            return TrialBalanceMovement(
        )
        """

    def testTrialBalanceMovement(self):
        """Test TrialBalanceMovement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
