# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.api.asset_api import AssetApi  # noqa: E501


class TestAssetApi(unittest.IsolatedAsyncioTestCase):
    """AssetApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AssetApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_create_asset(self) -> None:
        """Test case for create_asset

        adds a fixed asset  # noqa: E501
        """
        pass

    async def test_create_asset_type(self) -> None:
        """Test case for create_asset_type

        adds a fixed asset type  # noqa: E501
        """
        pass

    async def test_get_asset_by_id(self) -> None:
        """Test case for get_asset_by_id

        Retrieves fixed asset by id  # noqa: E501
        """
        pass

    async def test_get_asset_types(self) -> None:
        """Test case for get_asset_types

        searches fixed asset types  # noqa: E501
        """
        pass

    async def test_get_assets(self) -> None:
        """Test case for get_assets

        searches fixed asset  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
