# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.bank_transfer import BankTransfer  # noqa: E501


class TestBankTransfer(unittest.TestCase):
    """BankTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankTransfer:
        """Test BankTransfer
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BankTransfer`
        """
        model = BankTransfer()  # noqa: E501
        if include_optional:
            return BankTransfer(
                from_bank_account = xero_python.models.account.Account(
                    code = '4400', 
                    name = 'Food Sales', 
                    account_id = '00000000-0000-0000-0000-000000000000', 
                    type = 'BANK', 
                    bank_account_number = '', 
                    status = 'ACTIVE', 
                    description = '', 
                    bank_account_type = 'BANK', 
                    currency_code = 'AED', 
                    tax_type = '', 
                    enable_payments_to_account = True, 
                    show_in_expense_claims = True, 
                    class = 'ASSET', 
                    system_account = 'DEBTORS', 
                    reporting_code = '', 
                    reporting_code_name = '', 
                    has_attachments = False, 
                    updated_date_utc = '/Date(1573755038314)/', 
                    add_to_watchlist = True, 
                    validation_errors = [
                        xero_python.models.validation_error.ValidationError(
                            message = '', )
                        ], ),
                to_bank_account = xero_python.models.account.Account(
                    code = '4400', 
                    name = 'Food Sales', 
                    account_id = '00000000-0000-0000-0000-000000000000', 
                    type = 'BANK', 
                    bank_account_number = '', 
                    status = 'ACTIVE', 
                    description = '', 
                    bank_account_type = 'BANK', 
                    currency_code = 'AED', 
                    tax_type = '', 
                    enable_payments_to_account = True, 
                    show_in_expense_claims = True, 
                    class = 'ASSET', 
                    system_account = 'DEBTORS', 
                    reporting_code = '', 
                    reporting_code_name = '', 
                    has_attachments = False, 
                    updated_date_utc = '/Date(1573755038314)/', 
                    add_to_watchlist = True, 
                    validation_errors = [
                        xero_python.models.validation_error.ValidationError(
                            message = '', )
                        ], ),
                amount = 1.337,
                var_date = '',
                bank_transfer_id = '',
                currency_rate = 1.337,
                from_bank_transaction_id = '',
                to_bank_transaction_id = '',
                from_is_reconciled = False,
                to_is_reconciled = False,
                reference = '',
                has_attachments = False,
                created_date_utc = '/Date(1573755038314)/',
                validation_errors = [
                    xero_python.models.validation_error.ValidationError(
                        message = '', )
                    ]
            )
        else:
            return BankTransfer(
                from_bank_account = xero_python.models.account.Account(
                    code = '4400', 
                    name = 'Food Sales', 
                    account_id = '00000000-0000-0000-0000-000000000000', 
                    type = 'BANK', 
                    bank_account_number = '', 
                    status = 'ACTIVE', 
                    description = '', 
                    bank_account_type = 'BANK', 
                    currency_code = 'AED', 
                    tax_type = '', 
                    enable_payments_to_account = True, 
                    show_in_expense_claims = True, 
                    class = 'ASSET', 
                    system_account = 'DEBTORS', 
                    reporting_code = '', 
                    reporting_code_name = '', 
                    has_attachments = False, 
                    updated_date_utc = '/Date(1573755038314)/', 
                    add_to_watchlist = True, 
                    validation_errors = [
                        xero_python.models.validation_error.ValidationError(
                            message = '', )
                        ], ),
                to_bank_account = xero_python.models.account.Account(
                    code = '4400', 
                    name = 'Food Sales', 
                    account_id = '00000000-0000-0000-0000-000000000000', 
                    type = 'BANK', 
                    bank_account_number = '', 
                    status = 'ACTIVE', 
                    description = '', 
                    bank_account_type = 'BANK', 
                    currency_code = 'AED', 
                    tax_type = '', 
                    enable_payments_to_account = True, 
                    show_in_expense_claims = True, 
                    class = 'ASSET', 
                    system_account = 'DEBTORS', 
                    reporting_code = '', 
                    reporting_code_name = '', 
                    has_attachments = False, 
                    updated_date_utc = '/Date(1573755038314)/', 
                    add_to_watchlist = True, 
                    validation_errors = [
                        xero_python.models.validation_error.ValidationError(
                            message = '', )
                        ], ),
                amount = 1.337,
        )
        """

    def testBankTransfer(self):
        """Test BankTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
