# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.time_entry import TimeEntry  # noqa: E501


class TestTimeEntry(unittest.TestCase):
    """TimeEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeEntry:
        """Test TimeEntry
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TimeEntry`
        """
        model = TimeEntry()  # noqa: E501
        if include_optional:
            return TimeEntry(
                time_entry_id = '00000000-0000-0000-0000-000000000000',
                user_id = '00000000-0000-0000-0000-000000000000',
                project_id = '00000000-0000-0000-0000-000000000000',
                task_id = '00000000-0000-0000-0000-000000000000',
                date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_entered_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration = 56,
                description = '',
                status = 'ACTIVE'
            )
        else:
            return TimeEntry(
        )
        """

    def testTimeEntry(self):
        """Test TimeEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
