# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.project_create_or_update import ProjectCreateOrUpdate  # noqa: E501


class TestProjectCreateOrUpdate(unittest.TestCase):
    """ProjectCreateOrUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectCreateOrUpdate:
        """Test ProjectCreateOrUpdate
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProjectCreateOrUpdate`
        """
        model = ProjectCreateOrUpdate()  # noqa: E501
        if include_optional:
            return ProjectCreateOrUpdate(
                contact_id = '01234567-89ab-cdef-0123-456789abcdef',
                name = 'New Kitchen',
                estimate_amount = 1.0,
                deadline_utc = '2019-12-10T12:59:59Z'
            )
        else:
            return ProjectCreateOrUpdate(
                name = 'New Kitchen',
        )
        """

    def testProjectCreateOrUpdate(self):
        """Test ProjectCreateOrUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
