# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.organisations import Organisations  # noqa: E501


class TestOrganisations(unittest.TestCase):
    """Organisations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Organisations:
        """Test Organisations
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Organisations`
        """
        model = Organisations()  # noqa: E501
        if include_optional:
            return Organisations(
                organisations = [
                    xero_python.models.organisation.Organisation(
                        organisation_id = '8be9db36-3598-4755-ba5c-c2dbc8c4a7a2', 
                        api_key = '', 
                        name = '', 
                        legal_name = '', 
                        pays_tax = True, 
                        version = 'AU', 
                        organisation_type = 'ACCOUNTING_PRACTICE', 
                        base_currency = 'AED', 
                        country_code = 'AD', 
                        is_demo_company = True, 
                        organisation_status = '', 
                        registration_number = '', 
                        employer_identification_number = '', 
                        tax_number = '', 
                        financial_year_end_day = 56, 
                        financial_year_end_month = 56, 
                        sales_tax_basis = 'PAYMENTS', 
                        sales_tax_period = 'MONTHLY', 
                        default_sales_tax = '', 
                        default_purchases_tax = '', 
                        period_lock_date = '', 
                        end_of_year_lock_date = '', 
                        created_date_utc = '/Date(1573755038314)/', 
                        timezone = 'AFGHANISTANSTANDARDTIME', 
                        organisation_entity_type = 'ACCOUNTING_PRACTICE', 
                        short_code = '', 
                        class = 'DEMO', 
                        edition = 'BUSINESS', 
                        line_of_business = '', 
                        addresses = [
                            xero_python.models.address_for_organisation.AddressForOrganisation(
                                address_type = 'POBOX', 
                                address_line1 = '', 
                                address_line2 = '', 
                                address_line3 = '', 
                                address_line4 = '', 
                                city = '', 
                                region = '', 
                                postal_code = '', 
                                country = '', 
                                attention_to = '', )
                            ], 
                        phones = [
                            xero_python.models.phone.Phone(
                                phone_type = 'DEFAULT', 
                                phone_number = '', 
                                phone_area_code = '', 
                                phone_country_code = '', )
                            ], 
                        external_links = [
                            xero_python.models.external_link.ExternalLink(
                                link_type = 'Facebook', 
                                url = '', 
                                description = '', )
                            ], 
                        payment_terms = xero_python.models.payment_term.PaymentTerm(
                            bills = xero_python.models.bill.Bill(
                                day = 56, 
                                type = 'DAYSAFTERBILLDATE', ), 
                            sales = xero_python.models.bill.Bill(
                                day = 56, ), ), )
                    ]
            )
        else:
            return Organisations(
        )
        """

    def testOrganisations(self):
        """Test Organisations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
