# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.account_usage_response import AccountUsageResponse  # noqa: E501


class TestAccountUsageResponse(unittest.TestCase):
    """AccountUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountUsageResponse:
        """Test AccountUsageResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AccountUsageResponse`
        """
        model = AccountUsageResponse()  # noqa: E501
        if include_optional:
            return AccountUsageResponse(
                organisation_id = '',
                start_month = '',
                end_month = '',
                account_usage = [
                    xero_python.models.account_usage.AccountUsage(
                        month = '', 
                        account_id = '', 
                        currency_code = '', 
                        total_received = 1.337, 
                        count_received = 56, 
                        total_paid = 1.337, 
                        count_paid = 56, 
                        total_manual_journal = 1.337, 
                        count_manual_journal = 56, 
                        account_name = '', 
                        reporting_code = '', 
                        reporting_code_name = '', 
                        report_code_updated_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return AccountUsageResponse(
        )
        """

    def testAccountUsageResponse(self):
        """Test AccountUsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
