# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.contacts import Contacts  # noqa: E501


class TestContacts(unittest.TestCase):
    """Contacts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Contacts:
        """Test Contacts
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Contacts`
        """
        model = Contacts()  # noqa: E501
        if include_optional:
            return Contacts(
                pagination = xero_python.models.pagination_1.Pagination_1(
                    page = 56, 
                    page_size = 56, 
                    page_count = 56, 
                    item_count = 56, ),
                warnings = [
                    xero_python.models.validation_error.ValidationError(
                        message = '', )
                    ],
                contacts = [
                    xero_python.models.contact.Contact(
                        contact_id = '', 
                        merged_to_contact_id = '', 
                        contact_number = '', 
                        account_number = '', 
                        contact_status = 'ACTIVE', 
                        name = '', 
                        first_name = '', 
                        last_name = '', 
                        company_number = '', 
                        email_address = '', 
                        contact_persons = [
                            xero_python.models.contact_person.ContactPerson(
                                first_name = '', 
                                last_name = '', 
                                email_address = '', 
                                include_in_emails = True, )
                            ], 
                        bank_account_details = '', 
                        tax_number = '', 
                        accounts_receivable_tax_type = '', 
                        accounts_payable_tax_type = '', 
                        addresses = [
                            xero_python.models.address.Address(
                                address_type = 'POBOX', 
                                address_line1 = '', 
                                address_line2 = '', 
                                address_line3 = '', 
                                address_line4 = '', 
                                city = '', 
                                region = '', 
                                postal_code = '', 
                                country = '', 
                                attention_to = '', )
                            ], 
                        phones = [
                            xero_python.models.phone.Phone(
                                phone_type = 'DEFAULT', 
                                phone_number = '', 
                                phone_area_code = '', 
                                phone_country_code = '', )
                            ], 
                        is_supplier = True, 
                        is_customer = True, 
                        sales_default_line_amount_type = 'INCLUSIVE', 
                        purchases_default_line_amount_type = 'INCLUSIVE', 
                        default_currency = 'AED', 
                        xero_network_key = '', 
                        sales_default_account_code = '', 
                        purchases_default_account_code = '', 
                        sales_tracking_categories = [
                            xero_python.models.sales_tracking_category.SalesTrackingCategory(
                                tracking_category_name = '', 
                                tracking_option_name = '', )
                            ], 
                        purchases_tracking_categories = [
                            xero_python.models.sales_tracking_category.SalesTrackingCategory(
                                tracking_category_name = '', 
                                tracking_option_name = '', )
                            ], 
                        tracking_category_name = '', 
                        tracking_category_option = '', 
                        payment_terms = xero_python.models.payment_term.PaymentTerm(
                            bills = xero_python.models.bill.Bill(
                                day = 56, 
                                type = 'DAYSAFTERBILLDATE', ), 
                            sales = xero_python.models.bill.Bill(
                                day = 56, ), ), 
                        updated_date_utc = '/Date(1573755038314)/', 
                        contact_groups = [
                            xero_python.models.contact_group.ContactGroup(
                                name = '', 
                                status = 'ACTIVE', 
                                contact_group_id = '', 
                                contacts = [
                                    xero_python.models.contact.Contact(
                                        contact_id = '', 
                                        merged_to_contact_id = '', 
                                        contact_number = '', 
                                        account_number = '', 
                                        contact_status = 'ACTIVE', 
                                        name = '', 
                                        first_name = '', 
                                        last_name = '', 
                                        company_number = '', 
                                        email_address = '', 
                                        bank_account_details = '', 
                                        tax_number = '', 
                                        accounts_receivable_tax_type = '', 
                                        accounts_payable_tax_type = '', 
                                        is_supplier = True, 
                                        is_customer = True, 
                                        sales_default_line_amount_type = 'INCLUSIVE', 
                                        purchases_default_line_amount_type = 'INCLUSIVE', 
                                        xero_network_key = '', 
                                        sales_default_account_code = '', 
                                        purchases_default_account_code = '', 
                                        tracking_category_name = '', 
                                        tracking_category_option = '', 
                                        updated_date_utc = '/Date(1573755038314)/', 
                                        website = '', 
                                        branding_theme = xero_python.models.branding_theme.BrandingTheme(
                                            branding_theme_id = '', 
                                            name = '', 
                                            logo_url = '', 
                                            sort_order = 56, 
                                            created_date_utc = '/Date(1573755038314)/', ), 
                                        batch_payments = xero_python.models.batch_payment_details.BatchPaymentDetails(
                                            bank_account_number = '123-456-1111111', 
                                            bank_account_name = 'ACME Bank', 
                                            details = 'Hello World', 
                                            code = 'ABC', 
                                            reference = 'Foobar', ), 
                                        discount = 1.337, 
                                        balances = xero_python.models.balances.Balances(
                                            accounts_receivable = xero_python.models.accounts_receivable.AccountsReceivable(
                                                outstanding = 1.337, 
                                                overdue = 1.337, ), 
                                            accounts_payable = xero_python.models.accounts_payable.AccountsPayable(
                                                outstanding = 1.337, 
                                                overdue = 1.337, ), ), 
                                        attachments = [
                                            xero_python.models.attachment.Attachment(
                                                attachment_id = '00000000-0000-0000-0000-000000000000', 
                                                file_name = 'xero-dev.jpg', 
                                                url = 'https://api.xero.com/api.xro/2.0/Accounts/da962997-a8bd-4dff-9616-01cdc199283f/Attachments/sample5.jpg', 
                                                mime_type = 'image/jpg', 
                                                content_length = 56, 
                                                include_online = True, )
                                            ], 
                                        has_attachments = False, 
                                        validation_errors = [
                                            xero_python.models.validation_error.ValidationError(
                                                message = '', )
                                            ], 
                                        has_validation_errors = False, 
                                        status_attribute_string = '', )
                                    ], )
                            ], 
                        website = '', 
                        branding_theme = xero_python.models.branding_theme.BrandingTheme(
                            branding_theme_id = '', 
                            name = '', 
                            logo_url = '', 
                            sort_order = 56, 
                            created_date_utc = '/Date(1573755038314)/', ), 
                        batch_payments = xero_python.models.batch_payment_details.BatchPaymentDetails(
                            bank_account_number = '123-456-1111111', 
                            bank_account_name = 'ACME Bank', 
                            details = 'Hello World', 
                            code = 'ABC', 
                            reference = 'Foobar', ), 
                        discount = 1.337, 
                        balances = xero_python.models.balances.Balances(), 
                        attachments = [
                            xero_python.models.attachment.Attachment(
                                attachment_id = '00000000-0000-0000-0000-000000000000', 
                                file_name = 'xero-dev.jpg', 
                                url = 'https://api.xero.com/api.xro/2.0/Accounts/da962997-a8bd-4dff-9616-01cdc199283f/Attachments/sample5.jpg', 
                                mime_type = 'image/jpg', 
                                content_length = 56, 
                                include_online = True, )
                            ], 
                        has_attachments = False, 
                        validation_errors = [
                            xero_python.models.validation_error.ValidationError(
                                message = '', )
                            ], 
                        has_validation_errors = False, 
                        status_attribute_string = '', )
                    ]
            )
        else:
            return Contacts(
        )
        """

    def testContacts(self):
        """Test Contacts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
