# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.api.app_store_api import AppStoreApi  # noqa: E501


class TestAppStoreApi(unittest.IsolatedAsyncioTestCase):
    """AppStoreApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AppStoreApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_get_subscription(self) -> None:
        """Test case for get_subscription

        Retrieves a subscription for a given subscriptionId  # noqa: E501
        """
        pass

    async def test_get_usage_records(self) -> None:
        """Test case for get_usage_records

        Gets all usage records related to the subscription  # noqa: E501
        """
        pass

    async def test_post_usage_records(self) -> None:
        """Test case for post_usage_records

        Send metered usage belonging to this subscription and subscription item  # noqa: E501
        """
        pass

    async def test_put_usage_records(self) -> None:
        """Test case for put_usage_records

        Update and existing metered usage belonging to this subscription and subscription item  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
