# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.sales_tracking_category import SalesTrackingCategory  # noqa: E501


class TestSalesTrackingCategory(unittest.TestCase):
    """SalesTrackingCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SalesTrackingCategory:
        """Test SalesTrackingCategory
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SalesTrackingCategory`
        """
        model = SalesTrackingCategory()  # noqa: E501
        if include_optional:
            return SalesTrackingCategory(
                tracking_category_name = '',
                tracking_option_name = ''
            )
        else:
            return SalesTrackingCategory(
        )
        """

    def testSalesTrackingCategory(self):
        """Test SalesTrackingCategory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
