# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.court_order_line import CourtOrderLine  # noqa: E501


class TestCourtOrderLine(unittest.TestCase):
    """CourtOrderLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CourtOrderLine:
        """Test CourtOrderLine
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CourtOrderLine`
        """
        model = CourtOrderLine()  # noqa: E501
        if include_optional:
            return CourtOrderLine(
                court_order_type_id = '',
                amount = 1.337
            )
        else:
            return CourtOrderLine(
        )
        """

    def testCourtOrderLine(self):
        """Test CourtOrderLine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
