# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.deduction import Deduction  # noqa: E501


class TestDeduction(unittest.TestCase):
    """Deduction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deduction:
        """Test Deduction
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Deduction`
        """
        model = Deduction()  # noqa: E501
        if include_optional:
            return Deduction(
                deduction_id = '',
                deduction_name = '',
                deduction_category = 'CapitalContributions',
                liability_account_id = '',
                current_record = True,
                standard_amount = 1.337,
                reduces_super_liability = True,
                reduces_tax_liability = True,
                calculation_type = 'FixedAmount',
                percentage = 1.337,
                subject_to_nic = True,
                subject_to_tax = True,
                is_reduced_by_basic_rate = True,
                apply_to_pension_calculations = True,
                is_calculating_on_qualifying_earnings = True,
                is_pension = True
            )
        else:
            return Deduction(
                deduction_name = '',
                liability_account_id = '',
        )
        """

    def testDeduction(self):
        """Test Deduction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
