# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.super_fund_product import SuperFundProduct  # noqa: E501


class TestSuperFundProduct(unittest.TestCase):
    """SuperFundProduct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuperFundProduct:
        """Test SuperFundProduct
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SuperFundProduct`
        """
        model = SuperFundProduct()  # noqa: E501
        if include_optional:
            return SuperFundProduct(
                abn = '839182848805',
                usi = '839182848805001',
                spin = 'NML0117AU',
                product_name = 'MLC Navigator Retirement Plan - Superannuation Service (including Series 2) (MLC Superannuation Fund)'
            )
        else:
            return SuperFundProduct(
        )
        """

    def testSuperFundProduct(self):
        """Test SuperFundProduct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
