# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.benefit1 import Benefit1  # noqa: E501


class TestBenefit1(unittest.TestCase):
    """Benefit1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Benefit1:
        """Test Benefit1
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Benefit1`
        """
        model = Benefit1()  # noqa: E501
        if include_optional:
            return Benefit1(
                id = '',
                name = '',
                category = 'KiwiSaver',
                liability_account_id = '',
                expense_account_id = '',
                calculation_type_nz = 'FixedAmount',
                standard_amount = 1.337,
                percentage = 1.337,
                company_max = 1.337,
                current_record = True
            )
        else:
            return Benefit1(
                name = '',
                category = 'KiwiSaver',
                liability_account_id = '',
                expense_account_id = '',
        )
        """

    def testBenefit1(self):
        """Test Benefit1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
