# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.deductions import Deductions  # noqa: E501


class TestDeductions(unittest.TestCase):
    """Deductions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deductions:
        """Test Deductions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Deductions`
        """
        model = Deductions()  # noqa: E501
        if include_optional:
            return Deductions(
                pagination = xero_python.models.pagination.Pagination(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                problem = xero_python.models.problem.Problem(
                    type = 'application/problem+json', 
                    title = 'BadRequest', 
                    status = '400', 
                    detail = 'Validation error occurred.', 
                    instance = '', 
                    invalid_fields = [
                        xero_python.models.invalid_field.InvalidField(
                            name = 'DateOfBirth', 
                            reason = 'The Date of Birth is required.', )
                        ], ),
                deductions = [
                    xero_python.models.deduction.Deduction(
                        deduction_id = '', 
                        deduction_name = '', 
                        deduction_category = 'CapitalContributions', 
                        liability_account_id = '', 
                        current_record = True, 
                        standard_amount = 1.337, 
                        reduces_super_liability = True, 
                        reduces_tax_liability = True, 
                        calculation_type = 'FixedAmount', 
                        percentage = 1.337, 
                        subject_to_nic = True, 
                        subject_to_tax = True, 
                        is_reduced_by_basic_rate = True, 
                        apply_to_pension_calculations = True, 
                        is_calculating_on_qualifying_earnings = True, 
                        is_pension = True, )
                    ]
            )
        else:
            return Deductions(
        )
        """

    def testDeductions(self):
        """Test Deductions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
