# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.api.payroll_au_api import PayrollAuApi  # noqa: E501


class TestPayrollAuApi(unittest.IsolatedAsyncioTestCase):
    """PayrollAuApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PayrollAuApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_approve_leave_application(self) -> None:
        """Test case for approve_leave_application

        Approve a requested leave application by a unique leave application id  # noqa: E501
        """
        pass

    async def test_create_leave_application(self) -> None:
        """Test case for create_leave_application

        Creates a leave application  # noqa: E501
        """
        pass

    async def test_create_pay_item(self) -> None:
        """Test case for create_pay_item

        Creates a pay item  # noqa: E501
        """
        pass

    async def test_create_payroll_calendar(self) -> None:
        """Test case for create_payroll_calendar

        Creates a Payroll Calendar  # noqa: E501
        """
        pass

    async def test_create_superfund(self) -> None:
        """Test case for create_superfund

        Creates a superfund  # noqa: E501
        """
        pass

    async def test_get_leave_application(self) -> None:
        """Test case for get_leave_application

        Retrieves a leave application by a unique leave application id  # noqa: E501
        """
        pass

    async def test_get_leave_applications(self) -> None:
        """Test case for get_leave_applications

        Retrieves leave applications  # noqa: E501
        """
        pass

    async def test_get_leave_applications_v2(self) -> None:
        """Test case for get_leave_applications_v2

        Retrieves leave applications including leave requests  # noqa: E501
        """
        pass

    async def test_get_pay_items(self) -> None:
        """Test case for get_pay_items

        Retrieves pay items  # noqa: E501
        """
        pass

    async def test_get_payroll_calendar(self) -> None:
        """Test case for get_payroll_calendar

        Retrieves payroll calendar by using a unique payroll calendar ID  # noqa: E501
        """
        pass

    async def test_get_payroll_calendars(self) -> None:
        """Test case for get_payroll_calendars

        Retrieves payroll calendars  # noqa: E501
        """
        pass

    async def test_get_payslip(self) -> None:
        """Test case for get_payslip

        Retrieves for a payslip by a unique payslip id  # noqa: E501
        """
        pass

    async def test_get_superfund(self) -> None:
        """Test case for get_superfund

        Retrieves a superfund by using a unique superfund ID  # noqa: E501
        """
        pass

    async def test_get_superfund_products(self) -> None:
        """Test case for get_superfund_products

        Retrieves superfund products  # noqa: E501
        """
        pass

    async def test_get_superfunds(self) -> None:
        """Test case for get_superfunds

        Retrieves superfunds  # noqa: E501
        """
        pass

    async def test_reject_leave_application(self) -> None:
        """Test case for reject_leave_application

        Reject a leave application by a unique leave application id  # noqa: E501
        """
        pass

    async def test_update_leave_application(self) -> None:
        """Test case for update_leave_application

        Updates a specific leave application  # noqa: E501
        """
        pass

    async def test_update_payslip(self) -> None:
        """Test case for update_payslip

        Updates a payslip  # noqa: E501
        """
        pass

    async def test_update_superfund(self) -> None:
        """Test case for update_superfund

        Updates a superfund  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
