# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestCountryCode1(unittest.TestCase):
    """CountryCode1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryCode1(self):
        """Test CountryCode1"""
        # inst = CountryCode1()


if __name__ == "__main__":
    unittest.main()
