# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.amount import Amount  # noqa: E501


class TestAmount(unittest.TestCase):
    """Amount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Amount:
        """Test Amount
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Amount`
        """
        model = Amount()  # noqa: E501
        if include_optional:
            return Amount(
                currency = 'AUD',
                value = 1.0
            )
        else:
            return Amount(
        )
        """

    def testAmount(self):
        """Test Amount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
