# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.branding_theme import BrandingTheme  # noqa: E501


class TestBrandingTheme(unittest.TestCase):
    """BrandingTheme unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandingTheme:
        """Test BrandingTheme
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BrandingTheme`
        """
        model = BrandingTheme()  # noqa: E501
        if include_optional:
            return BrandingTheme(
                branding_theme_id = '',
                name = '',
                logo_url = '',
                type = 'INVOICE',
                sort_order = 56,
                created_date_utc = '/Date(1573755038314)/'
            )
        else:
            return BrandingTheme(
        )
        """

    def testBrandingTheme(self):
        """Test BrandingTheme"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
