# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.api.project_api import ProjectApi  # noqa: E501


class TestProjectApi(unittest.IsolatedAsyncioTestCase):
    """ProjectApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProjectApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_create_project(self) -> None:
        """Test case for create_project

        Create one or more new projects  # noqa: E501
        """
        pass

    async def test_create_task(self) -> None:
        """Test case for create_task

        Allows you to create a task  # noqa: E501
        """
        pass

    async def test_create_time_entry(self) -> None:
        """Test case for create_time_entry

        Creates a time entry for a specific project  # noqa: E501
        """
        pass

    async def test_delete_task(self) -> None:
        """Test case for delete_task

        Allows you to delete a task  # noqa: E501
        """
        pass

    async def test_delete_time_entry(self) -> None:
        """Test case for delete_time_entry

        Deletes a time entry for a specific project  # noqa: E501
        """
        pass

    async def test_get_project(self) -> None:
        """Test case for get_project

        Retrieves a single project  # noqa: E501
        """
        pass

    async def test_get_project_users(self) -> None:
        """Test case for get_project_users

        Retrieves a list of all project users  # noqa: E501
        """
        pass

    async def test_get_projects(self) -> None:
        """Test case for get_projects

        Retrieves all projects  # noqa: E501
        """
        pass

    async def test_get_task(self) -> None:
        """Test case for get_task

        Retrieves a single project task  # noqa: E501
        """
        pass

    async def test_get_tasks(self) -> None:
        """Test case for get_tasks

        Retrieves all project tasks  # noqa: E501
        """
        pass

    async def test_get_time_entries(self) -> None:
        """Test case for get_time_entries

        Retrieves all time entries associated with a specific project  # noqa: E501
        """
        pass

    async def test_get_time_entry(self) -> None:
        """Test case for get_time_entry

        Retrieves a single time entry for a specific project  # noqa: E501
        """
        pass

    async def test_patch_project(self) -> None:
        """Test case for patch_project

        creates a project for the specified contact  # noqa: E501
        """
        pass

    async def test_update_project(self) -> None:
        """Test case for update_project

        Updates a specific project  # noqa: E501
        """
        pass

    async def test_update_task(self) -> None:
        """Test case for update_task

        Allows you to update a task  # noqa: E501
        """
        pass

    async def test_update_time_entry(self) -> None:
        """Test case for update_time_entry

        Updates a time entry for a specific project  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
