# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.book_depreciation_setting import BookDepreciationSetting  # noqa: E501


class TestBookDepreciationSetting(unittest.TestCase):
    """BookDepreciationSetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookDepreciationSetting:
        """Test BookDepreciationSetting
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BookDepreciationSetting`
        """
        model = BookDepreciationSetting()  # noqa: E501
        if include_optional:
            return BookDepreciationSetting(
                depreciation_method = 'StraightLine',
                averaging_method = 'ActualDays',
                depreciation_rate = 0.05,
                effective_life_years = 5,
                depreciation_calculation_method = 'None',
                depreciable_object_id = '68f17094-af97-4f1b-b36b-013b45b6ad3c',
                depreciable_object_type = 'Asset',
                book_effective_date_of_change_id = '68f17094-af97-4f1b-b36b-013b45b6ad3c'
            )
        else:
            return BookDepreciationSetting(
        )
        """

    def testBookDepreciationSetting(self):
        """Test BookDepreciationSetting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
