# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.user_response import UserResponse  # noqa: E501


class TestUserResponse(unittest.TestCase):
    """UserResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserResponse:
        """Test UserResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserResponse`
        """
        model = UserResponse()  # noqa: E501
        if include_optional:
            return UserResponse(
                user_id = '',
                user_created_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_login_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_external_partner = True,
                has_accountant_role = True,
                month_period = '',
                number_of_logins = 56,
                number_of_documents_created = 56,
                net_value_documents_created = 1.337,
                absolute_value_documents_created = 1.337,
                attached_practices = [
                    xero_python.models.practice_response.PracticeResponse(
                        xero_partner_since = 56, 
                        tier = '', 
                        location = '', 
                        organisation_count = 56, 
                        staff_certified = True, )
                    ],
                history_records = [
                    xero_python.models.history_record_response.HistoryRecordResponse(
                        changes = '', 
                        date_utc_string = '', 
                        date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user = '', 
                        details = '', )
                    ]
            )
        else:
            return UserResponse(
        )
        """

    def testUserResponse(self):
        """Test UserResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
