# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.project_patch import ProjectPatch  # noqa: E501


class TestProjectPatch(unittest.TestCase):
    """ProjectPatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectPatch:
        """Test ProjectPatch
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProjectPatch`
        """
        model = ProjectPatch()  # noqa: E501
        if include_optional:
            return ProjectPatch(
                status = 'INPROGRESS'
            )
        else:
            return ProjectPatch(
                status = 'INPROGRESS',
        )
        """

    def testProjectPatch(self):
        """Test ProjectPatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
