# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.problem1 import Problem1  # noqa: E501


class TestProblem1(unittest.TestCase):
    """Problem1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Problem1:
        """Test Problem1
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Problem1`
        """
        model = Problem1()  # noqa: E501
        if include_optional:
            return Problem1(
                type = 'NotSet',
                title = '',
                status = 56,
                detail = ''
            )
        else:
            return Problem1(
        )
        """

    def testProblem1(self):
        """Test Problem1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
