# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.pay_run_object import PayRunObject  # noqa: E501


class TestPayRunObject(unittest.TestCase):
    """PayRunObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayRunObject:
        """Test PayRunObject
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PayRunObject`
        """
        model = PayRunObject()  # noqa: E501
        if include_optional:
            return PayRunObject(
                pagination = xero_python.models.pagination.Pagination(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                problem = xero_python.models.problem.Problem(
                    type = 'application/problem+json', 
                    title = 'BadRequest', 
                    status = '400', 
                    detail = 'Validation error occurred.', 
                    instance = '', 
                    invalid_fields = [
                        xero_python.models.invalid_field.InvalidField(
                            name = 'DateOfBirth', 
                            reason = 'The Date of Birth is required.', )
                        ], ),
                pay_run = xero_python.models.pay_run.PayRun(
                    pay_run_id = '', 
                    payroll_calendar_id = '', 
                    period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    total_cost = 1.337, 
                    total_pay = 1.337, 
                    pay_run_status = 'Draft', 
                    pay_run_type = 'Scheduled', 
                    calendar_type = 'Weekly', 
                    posted_date_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    pay_slips = [
                        xero_python.models.payslip.Payslip(
                            pay_slip_id = '', 
                            employee_id = '', 
                            pay_run_id = '', 
                            last_edited = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            first_name = '', 
                            last_name = '', 
                            total_earnings = 1.337, 
                            gross_earnings = 1.337, 
                            total_pay = 1.337, 
                            total_employer_taxes = 1.337, 
                            total_employee_taxes = 1.337, 
                            total_deductions = 1.337, 
                            total_reimbursements = 1.337, 
                            total_court_orders = 1.337, 
                            total_benefits = 1.337, 
                            bacs_hash = '', 
                            payment_method = 'Cheque', 
                            earnings_lines = [
                                xero_python.models.earnings_line.EarningsLine(
                                    earnings_line_id = '', 
                                    earnings_rate_id = '', 
                                    display_name = '', 
                                    rate_per_unit = 1.337, 
                                    number_of_units = 1.337, 
                                    fixed_amount = 1.337, 
                                    amount = 1.337, 
                                    is_linked_to_timesheet = True, 
                                    is_average_daily_pay_rate = True, )
                                ], 
                            leave_earnings_lines = [
                                xero_python.models.leave_earnings_line.LeaveEarningsLine(
                                    earnings_rate_id = '', 
                                    rate_per_unit = 1.337, 
                                    number_of_units = 1.337, 
                                    fixed_amount = 1.337, 
                                    amount = 1.337, 
                                    is_linked_to_timesheet = True, )
                                ], 
                            timesheet_earnings_lines = [
                                xero_python.models.timesheet_earnings_line.TimesheetEarningsLine(
                                    earnings_rate_id = '', 
                                    rate_per_unit = 1.337, 
                                    number_of_units = 1.337, 
                                    fixed_amount = 1.337, 
                                    amount = 1.337, 
                                    is_linked_to_timesheet = True, )
                                ], 
                            deduction_lines = [
                                xero_python.models.deduction_line.DeductionLine(
                                    deduction_type_id = '', 
                                    amount = 1.337, 
                                    subject_to_tax = True, 
                                    percentage = 1.337, )
                                ], 
                            reimbursement_lines = [
                                xero_python.models.reimbursement_line.ReimbursementLine(
                                    reimbursement_type_id = '', 
                                    description = '', 
                                    amount = 1.337, )
                                ], 
                            leave_accrual_lines = [
                                xero_python.models.leave_accrual_line.LeaveAccrualLine(
                                    leave_type_id = '', 
                                    number_of_units = 1.337, )
                                ], 
                            benefit_lines = [
                                xero_python.models.benefit_line.BenefitLine(
                                    benefit_type_id = '', 
                                    display_name = '', 
                                    amount = 1.337, 
                                    fixed_amount = 1.337, 
                                    percentage = 1.337, )
                                ], 
                            payment_lines = [
                                xero_python.models.payment_line.PaymentLine(
                                    payment_line_id = '', 
                                    amount = 1.337, 
                                    account_number = '', 
                                    sort_code = '', 
                                    account_name = '', )
                                ], 
                            employee_tax_lines = [
                                xero_python.models.tax_line.TaxLine(
                                    tax_line_id = '', 
                                    description = '', 
                                    is_employer_tax = True, 
                                    amount = 1.337, 
                                    global_tax_type_id = '', 
                                    manual_adjustment = True, )
                                ], 
                            employer_tax_lines = [
                                xero_python.models.tax_line.TaxLine(
                                    tax_line_id = '', 
                                    description = '', 
                                    is_employer_tax = True, 
                                    amount = 1.337, 
                                    global_tax_type_id = '', 
                                    manual_adjustment = True, )
                                ], 
                            court_order_lines = [
                                xero_python.models.court_order_line.CourtOrderLine(
                                    court_order_type_id = '', 
                                    amount = 1.337, )
                                ], )
                        ], )
            )
        else:
            return PayRunObject(
        )
        """

    def testPayRunObject(self):
        """Test PayRunObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
