# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.tax_line import TaxLine  # noqa: E501


class TestTaxLine(unittest.TestCase):
    """TaxLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxLine:
        """Test TaxLine
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TaxLine`
        """
        model = TaxLine()  # noqa: E501
        if include_optional:
            return TaxLine(
                tax_line_id = '',
                description = '',
                is_employer_tax = True,
                amount = 1.337,
                global_tax_type_id = '',
                manual_adjustment = True
            )
        else:
            return TaxLine(
        )
        """

    def testTaxLine(self):
        """Test TaxLine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
