# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.balance_sheet_account_detail import BalanceSheetAccountDetail  # noqa: E501


class TestBalanceSheetAccountDetail(unittest.TestCase):
    """BalanceSheetAccountDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceSheetAccountDetail:
        """Test BalanceSheetAccountDetail
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BalanceSheetAccountDetail`
        """
        model = BalanceSheetAccountDetail()  # noqa: E501
        if include_optional:
            return BalanceSheetAccountDetail(
                code = '',
                account_id = '',
                name = '',
                reporting_code = '',
                total = 1.337
            )
        else:
            return BalanceSheetAccountDetail(
        )
        """

    def testBalanceSheetAccountDetail(self):
        """Test BalanceSheetAccountDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
