# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.pay_run_calendar import PayRunCalendar  # noqa: E501


class TestPayRunCalendar(unittest.TestCase):
    """PayRunCalendar unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayRunCalendar:
        """Test PayRunCalendar
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PayRunCalendar`
        """
        model = PayRunCalendar()  # noqa: E501
        if include_optional:
            return PayRunCalendar(
                payroll_calendar_id = '',
                name = '',
                calendar_type = 'Weekly',
                period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                period_end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                updated_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PayRunCalendar(
                name = '',
                calendar_type = 'Weekly',
                period_start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                payment_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testPayRunCalendar(self):
        """Test PayRunCalendar"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
