# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.time_entries import TimeEntries  # noqa: E501


class TestTimeEntries(unittest.TestCase):
    """TimeEntries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeEntries:
        """Test TimeEntries
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TimeEntries`
        """
        model = TimeEntries()  # noqa: E501
        if include_optional:
            return TimeEntries(
                pagination = xero_python.models.pagination_2.Pagination_2(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                items = [
                    xero_python.models.time_entry.TimeEntry(
                        time_entry_id = '00000000-0000-0000-0000-000000000000', 
                        user_id = '00000000-0000-0000-0000-000000000000', 
                        project_id = '00000000-0000-0000-0000-000000000000', 
                        task_id = '00000000-0000-0000-0000-000000000000', 
                        date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_entered_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        duration = 56, 
                        description = '', 
                        status = 'ACTIVE', )
                    ]
            )
        else:
            return TimeEntries(
        )
        """

    def testTimeEntries(self):
        """Test TimeEntries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
