# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestProblemType(unittest.TestCase):
    """ProblemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemType(self):
        """Test ProblemType"""
        # inst = ProblemType()


if __name__ == "__main__":
    unittest.main()
