# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.batch_payment_details import BatchPaymentDetails  # noqa: E501


class TestBatchPaymentDetails(unittest.TestCase):
    """BatchPaymentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchPaymentDetails:
        """Test BatchPaymentDetails
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BatchPaymentDetails`
        """
        model = BatchPaymentDetails()  # noqa: E501
        if include_optional:
            return BatchPaymentDetails(
                bank_account_number = '123-456-1111111',
                bank_account_name = 'ACME Bank',
                details = 'Hello World',
                code = 'ABC',
                reference = 'Foobar'
            )
        else:
            return BatchPaymentDetails(
        )
        """

    def testBatchPaymentDetails(self):
        """Test BatchPaymentDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
