# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.tax_rates import TaxRates  # noqa: E501


class TestTaxRates(unittest.TestCase):
    """TaxRates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxRates:
        """Test TaxRates
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TaxRates`
        """
        model = TaxRates()  # noqa: E501
        if include_optional:
            return TaxRates(
                tax_rates = [
                    xero_python.models.tax_rate.TaxRate(
                        name = '', 
                        tax_type = '', 
                        tax_components = [
                            xero_python.models.tax_component.TaxComponent(
                                name = '', 
                                rate = 1.337, 
                                is_compound = True, 
                                is_non_recoverable = True, )
                            ], 
                        status = 'ACTIVE', 
                        report_tax_type = 'AVALARA', 
                        can_apply_to_assets = True, 
                        can_apply_to_equity = True, 
                        can_apply_to_expenses = True, 
                        can_apply_to_liabilities = True, 
                        can_apply_to_revenue = True, 
                        display_tax_rate = 1.337, 
                        effective_rate = 1.337, )
                    ]
            )
        else:
            return TaxRates(
        )
        """

    def testTaxRates(self):
        """Test TaxRates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
