# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.ten_ninety_nine_contact import TenNinetyNineContact  # noqa: E501


class TestTenNinetyNineContact(unittest.TestCase):
    """TenNinetyNineContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenNinetyNineContact:
        """Test TenNinetyNineContact
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TenNinetyNineContact`
        """
        model = TenNinetyNineContact()  # noqa: E501
        if include_optional:
            return TenNinetyNineContact(
                box1 = 1.337,
                box2 = 1.337,
                box3 = 1.337,
                box4 = 1.337,
                box5 = 1.337,
                box6 = 1.337,
                box7 = 1.337,
                box8 = 1.337,
                box9 = 1.337,
                box10 = 1.337,
                box11 = 1.337,
                box13 = 1.337,
                box14 = 1.337,
                name = '',
                federal_tax_id_type = '',
                city = '',
                zip = '',
                state = '',
                email = '',
                street_address = '',
                tax_id = '',
                contact_id = '',
                legal_name = '',
                business_name = '',
                federal_tax_classification = 'SOLE_PROPRIETOR'
            )
        else:
            return TenNinetyNineContact(
        )
        """

    def testTenNinetyNineContact(self):
        """Test TenNinetyNineContact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
