# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.employee_working_pattern_with_working_weeks_object import (
    EmployeeWorkingPatternWithWorkingWeeksObject,
)  # noqa: E501


class TestEmployeeWorkingPatternWithWorkingWeeksObject(unittest.TestCase):
    """EmployeeWorkingPatternWithWorkingWeeksObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> EmployeeWorkingPatternWithWorkingWeeksObject:
        """Test EmployeeWorkingPatternWithWorkingWeeksObject
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EmployeeWorkingPatternWithWorkingWeeksObject`
        """
        model = EmployeeWorkingPatternWithWorkingWeeksObject()  # noqa: E501
        if include_optional:
            return EmployeeWorkingPatternWithWorkingWeeksObject(
                pagination = xero_python.models.pagination.Pagination(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                problem = xero_python.models.problem.Problem(
                    type = 'application/problem+json', 
                    title = 'BadRequest', 
                    status = '400', 
                    detail = 'Validation error occurred.', 
                    instance = '', 
                    invalid_fields = [
                        xero_python.models.invalid_field.InvalidField(
                            name = 'DateOfBirth', 
                            reason = 'The Date of Birth is required.', )
                        ], ),
                payee_working_pattern = xero_python.models.employee_working_pattern_with_working_weeks.EmployeeWorkingPatternWithWorkingWeeks(
                    payee_working_pattern_id = '', 
                    effective_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    working_weeks = [
                        xero_python.models.working_week.WorkingWeek(
                            monday = 1.337, 
                            tuesday = 1.337, 
                            wednesday = 1.337, 
                            thursday = 1.337, 
                            friday = 1.337, 
                            saturday = 1.337, 
                            sunday = 1.337, )
                        ], )
            )
        else:
            return EmployeeWorkingPatternWithWorkingWeeksObject(
        )
        """

    def testEmployeeWorkingPatternWithWorkingWeeksObject(self):
        """Test EmployeeWorkingPatternWithWorkingWeeksObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
