# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.budgets import Budgets  # noqa: E501


class TestBudgets(unittest.TestCase):
    """Budgets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Budgets:
        """Test Budgets
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Budgets`
        """
        model = Budgets()  # noqa: E501
        if include_optional:
            return Budgets(
                budgets = [
                    xero_python.models.budget.Budget(
                        budget_id = '', 
                        type = 'OVERALL', 
                        description = '', 
                        updated_date_utc = '/Date(1573755038314)/', 
                        budget_lines = [
                            xero_python.models.budget_line.BudgetLine(
                                account_id = '', 
                                account_code = '090', 
                                budget_balances = [
                                    xero_python.models.budget_balance.BudgetBalance(
                                        period = '', 
                                        amount = 1.337, 
                                        unit_amount = 1.337, 
                                        notes = '', )
                                    ], )
                            ], 
                        tracking = [
                            xero_python.models.tracking_category.TrackingCategory(
                                tracking_category_id = '', 
                                tracking_option_id = '', 
                                name = '', 
                                option = '', 
                                status = 'ACTIVE', 
                                options = [
                                    xero_python.models.tracking_option.TrackingOption(
                                        tracking_option_id = '', 
                                        name = '', 
                                        status = 'ACTIVE', 
                                        tracking_category_id = '', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return Budgets(
        )
        """

    def testBudgets(self):
        """Test Budgets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
