# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.project import Project  # noqa: E501


class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Project:
        """Test Project
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Project`
        """
        model = Project()  # noqa: E501
        if include_optional:
            return Project(
                project_id = '254553fa-2be8-4991-bd5e-70a97ea12ef8',
                contact_id = '01234567-89ab-cdef-0123-456789abcdef',
                name = 'New Kitchen',
                currency_code = 'AUD',
                minutes_logged = 0,
                total_task_amount = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                total_expense_amount = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                estimate_amount = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                minutes_to_be_invoiced = 0,
                task_amount_to_be_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                task_amount_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                expense_amount_to_be_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                expense_amount_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                project_amount_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                deposit = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                deposit_applied = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                credit_note_amount = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                deadline_utc = '2019-12-10T12:59:59Z',
                total_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                total_to_be_invoiced = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                estimate = xero_python.models.amount.Amount(
                    currency = 'AUD', 
                    value = 1.0, ),
                status = 'INPROGRESS'
            )
        else:
            return Project(
                name = 'New Kitchen',
        )
        """

    def testProject(self):
        """Test Project"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
