# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.leave_types import LeaveTypes  # noqa: E501


class TestLeaveTypes(unittest.TestCase):
    """LeaveTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeaveTypes:
        """Test LeaveTypes
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `LeaveTypes`
        """
        model = LeaveTypes()  # noqa: E501
        if include_optional:
            return LeaveTypes(
                pagination = xero_python.models.pagination.Pagination(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                problem = xero_python.models.problem.Problem(
                    type = 'application/problem+json', 
                    title = 'BadRequest', 
                    status = '400', 
                    detail = 'Validation error occurred.', 
                    instance = '', 
                    invalid_fields = [
                        xero_python.models.invalid_field.InvalidField(
                            name = 'DateOfBirth', 
                            reason = 'The Date of Birth is required.', )
                        ], ),
                leave_types = [
                    xero_python.models.leave_type_1.LeaveType_1(
                        leave_id = '', 
                        leave_type_id = '', 
                        name = '', 
                        is_paid_leave = True, 
                        show_on_payslip = True, 
                        updated_date_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_active = True, 
                        is_statutory_leave = True, )
                    ]
            )
        else:
            return LeaveTypes(
        )
        """

    def testLeaveTypes(self):
        """Test LeaveTypes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
