# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.tracking_options import TrackingOptions  # noqa: E501


class TestTrackingOptions(unittest.TestCase):
    """TrackingOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrackingOptions:
        """Test TrackingOptions
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `TrackingOptions`
        """
        model = TrackingOptions()  # noqa: E501
        if include_optional:
            return TrackingOptions(
                options = [
                    xero_python.models.tracking_option.TrackingOption(
                        tracking_option_id = '', 
                        name = '', 
                        status = 'ACTIVE', 
                        tracking_category_id = '', )
                    ]
            )
        else:
            return TrackingOptions(
        )
        """

    def testTrackingOptions(self):
        """Test TrackingOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
