# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.earnings_rate import EarningsRate  # noqa: E501


class TestEarningsRate(unittest.TestCase):
    """EarningsRate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EarningsRate:
        """Test EarningsRate
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EarningsRate`
        """
        model = EarningsRate()  # noqa: E501
        if include_optional:
            return EarningsRate(
                earnings_rate_id = '',
                name = '',
                earnings_type = 'Allowance',
                rate_type = 'RatePerUnit',
                type_of_units = '',
                current_record = True,
                expense_account_id = '',
                rate_per_unit = 1.337,
                multiple_of_ordinary_earnings_rate = 1.337,
                fixed_amount = 1.337
            )
        else:
            return EarningsRate(
                name = '',
                earnings_type = 'Allowance',
                rate_type = 'RatePerUnit',
                type_of_units = '',
                expense_account_id = '',
        )
        """

    def testEarningsRate(self):
        """Test EarningsRate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
