# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.practice_response import PracticeResponse  # noqa: E501


class TestPracticeResponse(unittest.TestCase):
    """PracticeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PracticeResponse:
        """Test PracticeResponse
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PracticeResponse`
        """
        model = PracticeResponse()  # noqa: E501
        if include_optional:
            return PracticeResponse(
                xero_partner_since = 56,
                tier = '',
                location = '',
                organisation_count = 56,
                staff_certified = True
            )
        else:
            return PracticeResponse(
        )
        """

    def testPracticeResponse(self):
        """Test PracticeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
