# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest


class TestLeavePeriodStatus(unittest.TestCase):
    """LeavePeriodStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeavePeriodStatus(self):
        """Test LeavePeriodStatus"""
        # inst = LeavePeriodStatus()


if __name__ == "__main__":
    unittest.main()
