# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.report_row import ReportRow  # noqa: E501


class TestReportRow(unittest.TestCase):
    """ReportRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportRow:
        """Test ReportRow
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ReportRow`
        """
        model = ReportRow()  # noqa: E501
        if include_optional:
            return ReportRow(
                row_type = 'Header',
                title = '',
                cells = [
                    xero_python.models.report_cell.ReportCell(
                        value = '', 
                        attributes = [
                            xero_python.models.report_attribute.ReportAttribute(
                                id = '', 
                                value = '', )
                            ], )
                    ]
            )
        else:
            return ReportRow(
        )
        """

    def testReportRow(self):
        """Test ReportRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
