# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.employee_statutory_leaves_summaries import (
    EmployeeStatutoryLeavesSummaries,
)  # noqa: E501


class TestEmployeeStatutoryLeavesSummaries(unittest.TestCase):
    """EmployeeStatutoryLeavesSummaries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmployeeStatutoryLeavesSummaries:
        """Test EmployeeStatutoryLeavesSummaries
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EmployeeStatutoryLeavesSummaries`
        """
        model = EmployeeStatutoryLeavesSummaries()  # noqa: E501
        if include_optional:
            return EmployeeStatutoryLeavesSummaries(
                pagination = xero_python.models.pagination.Pagination(
                    page = 1, 
                    page_size = 10, 
                    page_count = 1, 
                    item_count = 2, ),
                problem = xero_python.models.problem.Problem(
                    type = 'application/problem+json', 
                    title = 'BadRequest', 
                    status = '400', 
                    detail = 'Validation error occurred.', 
                    instance = '', 
                    invalid_fields = [
                        xero_python.models.invalid_field.InvalidField(
                            name = 'DateOfBirth', 
                            reason = 'The Date of Birth is required.', )
                        ], ),
                statutory_leaves = [
                    xero_python.models.employee_statutory_leave_summary.EmployeeStatutoryLeaveSummary(
                        statutory_leave_id = '', 
                        employee_id = '', 
                        type = 'Sick', 
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        is_entitled = True, 
                        status = 'Pending', )
                    ]
            )
        else:
            return EmployeeStatutoryLeavesSummaries(
        )
        """

    def testEmployeeStatutoryLeavesSummaries(self):
        """Test EmployeeStatutoryLeavesSummaries"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
