# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.budget_line import BudgetLine  # noqa: E501


class TestBudgetLine(unittest.TestCase):
    """BudgetLine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BudgetLine:
        """Test BudgetLine
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BudgetLine`
        """
        model = BudgetLine()  # noqa: E501
        if include_optional:
            return BudgetLine(
                account_id = '',
                account_code = '090',
                budget_balances = [
                    xero_python.models.budget_balance.BudgetBalance(
                        period = '', 
                        amount = 1.337, 
                        unit_amount = 1.337, 
                        notes = '', )
                    ]
            )
        else:
            return BudgetLine(
        )
        """

    def testBudgetLine(self):
        """Test BudgetLine"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
