# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from xero_python.models.import_summary_object import ImportSummaryObject  # noqa: E501


class TestImportSummaryObject(unittest.TestCase):
    """ImportSummaryObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportSummaryObject:
        """Test ImportSummaryObject
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ImportSummaryObject`
        """
        model = ImportSummaryObject()  # noqa: E501
        if include_optional:
            return ImportSummaryObject(
                import_summary = xero_python.models.import_summary.ImportSummary(
                    accounts = xero_python.models.import_summary_accounts.ImportSummaryAccounts(
                        total = 56, 
                        new = 56, 
                        updated = 56, 
                        deleted = 56, 
                        locked = 56, 
                        system = 56, 
                        errored = 56, 
                        present = True, 
                        new_or_updated = 56, ), 
                    organisation = xero_python.models.import_summary_organisation.ImportSummaryOrganisation(
                        present = True, ), )
            )
        else:
            return ImportSummaryObject(
        )
        """

    def testImportSummaryObject(self):
        """Test ImportSummaryObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
