from enum import Enum


class PaymentTermType(Enum):
    DAYSAFTERBILLDATE = "DAYSAFTERBILLDATE"
    DAYSAFTERBILLMONTH = "DAYSAFTERBILLMONTH"
    OFCURRENTMONTH = "OFCURRENTMONTH"
    OFFOLLOWINGMONTH = "OFFOLLOWINGMONTH"
