"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist

from xero_python.models.statement_response import StatementResponse


class BankStatementAccountingResponse(BaseModel):
    """
    BankStatementAccountingResponse
    """

    bank_account_id: Optional[StrictStr] = Field(
        default=None, alias="bankAccountId", description="Xero Identifier of bank account"
    )
    bank_account_name: Optional[StrictStr] = Field(
        default=None, alias="bankAccountName", description="Name of bank account"
    )
    bank_account_currency_code: Optional[StrictStr] = Field(
        default=None, alias="bankAccountCurrencyCode", description="Currency code of the bank account"
    )
    statements: Optional[conlist(StatementResponse)] = Field(
        default=None, description="List of bank statements and linked accounting data for the requested period"
    )
    __properties = ["bankAccountId", "bankAccountName", "bankAccountCurrencyCode", "statements"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BankStatementAccountingResponse:
        """Create an instance of BankStatementAccountingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in statements (list)
        _items = []
        if self.statements:
            for _item in self.statements:
                if _item:
                    _items.append(_item.to_dict())
            _dict["statements"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BankStatementAccountingResponse:
        """Create an instance of BankStatementAccountingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BankStatementAccountingResponse.parse_obj(obj)

        _obj = BankStatementAccountingResponse.parse_obj(
            {
                "bank_account_id": obj.get("bankAccountId"),
                "bank_account_name": obj.get("bankAccountName"),
                "bank_account_currency_code": obj.get("bankAccountCurrencyCode"),
                "statements": [StatementResponse.from_dict(_item) for _item in obj.get("statements")]
                if obj.get("statements") is not None
                else None,
            }
        )
        return _obj
