"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, conlist

from xero_python.models.bank_transfer import BankTransfer


class BankTransfers(BaseModel):
    """
    BankTransfers
    """

    bank_transfers: Optional[conlist(BankTransfer)] = Field(default=None, alias="BankTransfers")
    __properties = ["BankTransfers"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BankTransfers:
        """Create an instance of BankTransfers from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in bank_transfers (list)
        _items = []
        if self.bank_transfers:
            for _item in self.bank_transfers:
                if _item:
                    _items.append(_item.to_dict())
            _dict["BankTransfers"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BankTransfers:
        """Create an instance of BankTransfers from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BankTransfers.parse_obj(obj)

        _obj = BankTransfers.parse_obj(
            {
                "bank_transfers": [BankTransfer.from_dict(_item) for _item in obj.get("BankTransfers")]
                if obj.get("BankTransfers") is not None
                else None
            }
        )
        return _obj
