"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field

from xero_python.models.current_statement_response import CurrentStatementResponse
from xero_python.models.statement_lines_response import StatementLinesResponse


class BankStatementResponse(BaseModel):
    """
    BankStatementResponse
    """

    statement_lines: Optional[StatementLinesResponse] = Field(default=None, alias="statementLines")
    current_statement: Optional[CurrentStatementResponse] = Field(default=None, alias="currentStatement")
    __properties = ["statementLines", "currentStatement"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BankStatementResponse:
        """Create an instance of BankStatementResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of statement_lines
        if self.statement_lines:
            _dict["statementLines"] = self.statement_lines.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current_statement
        if self.current_statement:
            _dict["currentStatement"] = self.current_statement.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BankStatementResponse:
        """Create an instance of BankStatementResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BankStatementResponse.parse_obj(obj)

        _obj = BankStatementResponse.parse_obj(
            {
                "statement_lines": StatementLinesResponse.from_dict(obj.get("statementLines"))
                if obj.get("statementLines") is not None
                else None,
                "current_statement": CurrentStatementResponse.from_dict(obj.get("currentStatement"))
                if obj.get("currentStatement") is not None
                else None,
            }
        )
        return _obj
