"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt


class BookDepreciationDetail(BaseModel):
    """
    BookDepreciationDetail
    """

    current_capital_gain: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="currentCapitalGain",
        description="When an asset is disposed, this will be the sell price minus the purchase price if a profit was made.",
    )
    current_gain_loss: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="currentGainLoss",
        description="When an asset is disposed, this will be the lowest one of sell price or purchase price, minus the current book value.",
    )
    depreciation_start_date: Optional[date] = Field(
        default=None, alias="depreciationStartDate", description="YYYY-MM-DD"
    )
    cost_limit: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="costLimit",
        description="The value of the asset you want to depreciate, if this is less than the cost of the asset.",
    )
    residual_value: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="residualValue",
        description="The value of the asset remaining when you've fully depreciated it.",
    )
    prior_accum_depreciation_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="priorAccumDepreciationAmount",
        description="All depreciation prior to the current financial year.",
    )
    current_accum_depreciation_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="currentAccumDepreciationAmount",
        description="All depreciation occurring in the current financial year.",
    )
    __properties = [
        "currentCapitalGain",
        "currentGainLoss",
        "depreciationStartDate",
        "costLimit",
        "residualValue",
        "priorAccumDepreciationAmount",
        "currentAccumDepreciationAmount",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BookDepreciationDetail:
        """Create an instance of BookDepreciationDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BookDepreciationDetail:
        """Create an instance of BookDepreciationDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BookDepreciationDetail.parse_obj(obj)

        _obj = BookDepreciationDetail.parse_obj(
            {
                "current_capital_gain": obj.get("currentCapitalGain"),
                "current_gain_loss": obj.get("currentGainLoss"),
                "depreciation_start_date": obj.get("depreciationStartDate"),
                "cost_limit": obj.get("costLimit"),
                "residual_value": obj.get("residualValue"),
                "prior_accum_depreciation_amount": obj.get("priorAccumDepreciationAmount"),
                "current_accum_depreciation_amount": obj.get("currentAccumDepreciationAmount"),
            }
        )
        return _obj
