"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictInt, StrictStr, validator


class BrandingTheme(BaseModel):
    """
    BrandingTheme
    """

    branding_theme_id: Optional[StrictStr] = Field(default=None, alias="BrandingThemeID", description="Xero identifier")
    name: Optional[StrictStr] = Field(default=None, alias="Name", description="Name of branding theme")
    logo_url: Optional[StrictStr] = Field(
        default=None,
        alias="LogoUrl",
        description="The location of the image file used as the logo on this branding theme",
    )
    type: Optional[StrictStr] = Field(default=None, alias="Type", description="Always INVOICE")
    sort_order: Optional[StrictInt] = Field(
        default=None,
        alias="SortOrder",
        description="Integer – ranked order of branding theme. The default branding theme has a value of 0",
    )
    created_date_utc: Optional[StrictStr] = Field(
        default=None, alias="CreatedDateUTC", description="UTC timestamp of creation date of branding theme"
    )
    __properties = ["BrandingThemeID", "Name", "LogoUrl", "Type", "SortOrder", "CreatedDateUTC"]

    @validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("INVOICE",):
            raise ValueError("must be one of enum values ('INVOICE')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BrandingTheme:
        """Create an instance of BrandingTheme from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={"created_date_utc"}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BrandingTheme:
        """Create an instance of BrandingTheme from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BrandingTheme.parse_obj(obj)

        _obj = BrandingTheme.parse_obj(
            {
                "branding_theme_id": obj.get("BrandingThemeID"),
                "name": obj.get("Name"),
                "logo_url": obj.get("LogoUrl"),
                "type": obj.get("Type"),
                "sort_order": obj.get("SortOrder"),
                "created_date_utc": obj.get("CreatedDateUTC"),
            }
        )
        return _obj
