"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist

from xero_python.models.budget_balance import BudgetBalance


class BudgetLine(BaseModel):
    """
    BudgetLine
    """

    account_id: Optional[StrictStr] = Field(default=None, alias="AccountID", description="See Accounts")
    account_code: Optional[StrictStr] = Field(default=None, alias="AccountCode", description="See Accounts")
    budget_balances: Optional[conlist(BudgetBalance)] = Field(default=None, alias="BudgetBalances")
    __properties = ["AccountID", "AccountCode", "BudgetBalances"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BudgetLine:
        """Create an instance of BudgetLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in budget_balances (list)
        _items = []
        if self.budget_balances:
            for _item in self.budget_balances:
                if _item:
                    _items.append(_item.to_dict())
            _dict["BudgetBalances"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BudgetLine:
        """Create an instance of BudgetLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BudgetLine.parse_obj(obj)

        _obj = BudgetLine.parse_obj(
            {
                "account_id": obj.get("AccountID"),
                "account_code": obj.get("AccountCode"),
                "budget_balances": [BudgetBalance.from_dict(_item) for _item in obj.get("BudgetBalances")]
                if obj.get("BudgetBalances") is not None
                else None,
            }
        )
        return _obj
