"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist

from xero_python.models.cashflow_type import CashflowType


class CashflowActivity(BaseModel):
    """
    CashflowActivity
    """

    name: Optional[StrictStr] = Field(
        default=None,
        description="Name of the cashflow activity type. It will be either Operating Activities, Investing Activities or Financing Activities",
    )
    total: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total value of the activity type")
    cashflow_types: Optional[conlist(CashflowType)] = Field(default=None, alias="cashflowTypes")
    __properties = ["name", "total", "cashflowTypes"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CashflowActivity:
        """Create an instance of CashflowActivity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in cashflow_types (list)
        _items = []
        if self.cashflow_types:
            for _item in self.cashflow_types:
                if _item:
                    _items.append(_item.to_dict())
            _dict["cashflowTypes"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CashflowActivity:
        """Create an instance of CashflowActivity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CashflowActivity.parse_obj(obj)

        _obj = CashflowActivity.parse_obj(
            {
                "name": obj.get("name"),
                "total": obj.get("total"),
                "cashflow_types": [CashflowType.from_dict(_item) for _item in obj.get("cashflowTypes")]
                if obj.get("cashflowTypes") is not None
                else None,
            }
        )
        return _obj
