"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional

from pydantic import BaseModel, Field, conlist

from xero_python.models.cash_balance import CashBalance
from xero_python.models.cashflow_activity import CashflowActivity


class CashflowResponse(BaseModel):
    """
    CashflowResponse
    """

    start_date: Optional[date] = Field(default=None, alias="startDate", description="Start date of the report")
    end_date: Optional[date] = Field(default=None, alias="endDate", description="End date of the report")
    cash_balance: Optional[CashBalance] = Field(default=None, alias="cashBalance")
    cashflow_activities: Optional[conlist(CashflowActivity)] = Field(
        default=None, alias="cashflowActivities", description="Break down of cash and cash equivalents for the period"
    )
    __properties = ["startDate", "endDate", "cashBalance", "cashflowActivities"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CashflowResponse:
        """Create an instance of CashflowResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of cash_balance
        if self.cash_balance:
            _dict["cashBalance"] = self.cash_balance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in cashflow_activities (list)
        _items = []
        if self.cashflow_activities:
            for _item in self.cashflow_activities:
                if _item:
                    _items.append(_item.to_dict())
            _dict["cashflowActivities"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CashflowResponse:
        """Create an instance of CashflowResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CashflowResponse.parse_obj(obj)

        _obj = CashflowResponse.parse_obj(
            {
                "start_date": obj.get("startDate"),
                "end_date": obj.get("endDate"),
                "cash_balance": CashBalance.from_dict(obj.get("cashBalance"))
                if obj.get("cashBalance") is not None
                else None,
                "cashflow_activities": [CashflowActivity.from_dict(_item) for _item in obj.get("cashflowActivities")]
                if obj.get("cashflowActivities") is not None
                else None,
            }
        )
        return _obj
