"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt


class ContactTotalDetail(BaseModel):
    """
    ContactTotalDetail
    """

    total_paid: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="totalPaid",
        description="Total paid invoice and cash value for the contact within the period.",
    )
    total_outstanding: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="totalOutstanding",
        description="Total outstanding invoice value for the contact within the period.",
    )
    total_credited_un_applied: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="totalCreditedUnApplied",
        description="Total unapplied credited value for the contact within the period.",
    )
    __properties = ["totalPaid", "totalOutstanding", "totalCreditedUnApplied"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ContactTotalDetail:
        """Create an instance of ContactTotalDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ContactTotalDetail:
        """Create an instance of ContactTotalDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ContactTotalDetail.parse_obj(obj)

        _obj = ContactTotalDetail.parse_obj(
            {
                "total_paid": obj.get("totalPaid"),
                "total_outstanding": obj.get("totalOutstanding"),
                "total_credited_un_applied": obj.get("totalCreditedUnApplied"),
            }
        )
        return _obj
