"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist, validator


class ContactGroup(BaseModel):
    """
    ContactGroup
    """

    name: Optional[StrictStr] = Field(
        default=None,
        alias="Name",
        description="The Name of the contact group. Required when creating a new contact  group",
    )
    status: Optional[StrictStr] = Field(
        default=None,
        alias="Status",
        description="The Status of a contact group. To delete a contact group update the status to DELETED. Only contact groups with a status of ACTIVE are returned on GETs.",
    )
    contact_group_id: Optional[StrictStr] = Field(
        default=None,
        alias="ContactGroupID",
        description="The Xero identifier for an contact group – specified as a string following the endpoint name. e.g. /297c2dc5-cc47-4afd-8ec8-74990b8761e9",
    )
    contacts: Optional[conlist(Contact)] = Field(
        default=None,
        alias="Contacts",
        description="The ContactID and Name of Contacts in a contact group. Returned on GETs when the ContactGroupID is supplied in the URL.",
    )
    __properties = ["Name", "Status", "ContactGroupID", "Contacts"]

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("ACTIVE", "DELETED"):
            raise ValueError("must be one of enum values ('ACTIVE', 'DELETED')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ContactGroup:
        """Create an instance of ContactGroup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in contacts (list)
        _items = []
        if self.contacts:
            for _item in self.contacts:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Contacts"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ContactGroup:
        """Create an instance of ContactGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ContactGroup.parse_obj(obj)

        _obj = ContactGroup.parse_obj(
            {
                "name": obj.get("Name"),
                "status": obj.get("Status"),
                "contact_group_id": obj.get("ContactGroupID"),
                "contacts": [Contact.from_dict(_item) for _item in obj.get("Contacts")]
                if obj.get("Contacts") is not None
                else None,
            }
        )
        return _obj


from xero_python.models.contact import Contact

ContactGroup.update_forward_refs()
