"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr


class CourtOrderLine(BaseModel):
    """
    CourtOrderLine
    """

    court_order_type_id: Optional[StrictStr] = Field(
        default=None, alias="courtOrderTypeID", description="Xero identifier for payroll court order type"
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount")
    __properties = ["courtOrderTypeID", "amount"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CourtOrderLine:
        """Create an instance of CourtOrderLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CourtOrderLine:
        """Create an instance of CourtOrderLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CourtOrderLine.parse_obj(obj)

        _obj = CourtOrderLine.parse_obj(
            {"court_order_type_id": obj.get("courtOrderTypeID"), "amount": obj.get("amount")}
        )
        return _obj
