"""
merged spec

merged spec

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import json
import re  # noqa: F401

from aenum import Enum


class CreditDebitIndicator(str, Enum):
    """
    If the statement balances are credit or debit, the CreditDebitIndicator should be specified from the perspective of the Customer.
    """

    """
    allowed enum values
    """
    CREDIT = "CREDIT"
    DEBIT = "DEBIT"

    @classmethod
    def from_json(cls, json_str: str) -> "CreditDebitIndicator":
        """Create an instance of CreditDebitIndicator from a JSON string"""
        return CreditDebitIndicator(json.loads(json_str))
