"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt


class DataSourceResponse(BaseModel):
    """
    DataSourceResponse
    """

    direct_bank_feed: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="directBankFeed",
        description="Sum of the amounts of all statement lines where the source of the data was a direct bank feed in to Xero via an API integration.   This could be from a bank or aggregator.   This gives an indication on the certainty of correctness of the data.",
    )
    indirect_bank_feed: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="indirectBankFeed", description="No longer in use."
    )
    file_upload: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="fileUpload",
        description="Sum of the amounts of all statement lines where the source of the data was a file manually uploaded in to Xero.   This gives an indication on the certainty of correctness of the data.",
    )
    manual: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Sum of the amounts of all statement lines where the source of the data was manually input in to Xero.   This gives an indication on the certainty of correctness of the data.",
    )
    direct_bank_feed_pos: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="directBankFeedPos",
        description="Sum of the amounts of all statement lines where the source of the data was a direct bank feed in to Xero via an API integration.   This could be from a bank or aggregator.  This gives an indication on the certainty of correctness of the data.  Only positive transactions are included.",
    )
    indirect_bank_feed_pos: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="indirectBankFeedPos", description="No longer in use."
    )
    file_upload_pos: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="fileUploadPos",
        description="Sum of the amounts of all statement lines where the source of the data was a file manually uploaded in to Xero.   This gives an indication on the certainty of correctness of the data. Only positive transactions are included.",
    )
    manual_pos: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="manualPos",
        description="Sum of the amounts of all statement lines where the source of the data was manually input in to Xero.   This gives an indication on the certainty of correctness of the data. Only positive transactions are included.",
    )
    direct_bank_feed_neg: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="directBankFeedNeg",
        description="Sum of the amounts of all statement lines where the source of the data was a direct bank feed in to Xero via an API integration.   This could be from a bank or aggregator.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included.",
    )
    indirect_bank_feed_neg: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="indirectBankFeedNeg", description="No longer in use."
    )
    file_upload_neg: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="fileUploadNeg",
        description="Sum of the amounts of all statement lines where the source of the data was a file manually uploaded in to Xero.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included.",
    )
    manual_neg: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="manualNeg",
        description="Sum of the amounts of all statement lines where the source of the data was manually input in to Xero.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included.",
    )
    other_pos: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="otherPos",
        description="Sum of the amounts of all statement lines where the source of the data was unknown.   This gives an indication on the certainty of correctness of the data.  Only positive transactions are included.",
    )
    other_neg: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="otherNeg",
        description="Sum of the amounts of all statement lines where the source of the data was unknown.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included.",
    )
    other: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Sum of the amounts of all statement lines where the source of the data was unknown.   This gives an indication on the certainty of correctness of the data.",
    )
    __properties = [
        "directBankFeed",
        "indirectBankFeed",
        "fileUpload",
        "manual",
        "directBankFeedPos",
        "indirectBankFeedPos",
        "fileUploadPos",
        "manualPos",
        "directBankFeedNeg",
        "indirectBankFeedNeg",
        "fileUploadNeg",
        "manualNeg",
        "otherPos",
        "otherNeg",
        "other",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DataSourceResponse:
        """Create an instance of DataSourceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DataSourceResponse:
        """Create an instance of DataSourceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DataSourceResponse.parse_obj(obj)

        _obj = DataSourceResponse.parse_obj(
            {
                "direct_bank_feed": obj.get("directBankFeed"),
                "indirect_bank_feed": obj.get("indirectBankFeed"),
                "file_upload": obj.get("fileUpload"),
                "manual": obj.get("manual"),
                "direct_bank_feed_pos": obj.get("directBankFeedPos"),
                "indirect_bank_feed_pos": obj.get("indirectBankFeedPos"),
                "file_upload_pos": obj.get("fileUploadPos"),
                "manual_pos": obj.get("manualPos"),
                "direct_bank_feed_neg": obj.get("directBankFeedNeg"),
                "indirect_bank_feed_neg": obj.get("indirectBankFeedNeg"),
                "file_upload_neg": obj.get("fileUploadNeg"),
                "manual_neg": obj.get("manualNeg"),
                "other_pos": obj.get("otherPos"),
                "other_neg": obj.get("otherNeg"),
                "other": obj.get("other"),
            }
        )
        return _obj
