"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr


class DeductionLine(BaseModel):
    """
    DeductionLine
    """

    deduction_type_id: Optional[StrictStr] = Field(
        default=None, alias="deductionTypeID", description="Xero identifier for payroll deduction"
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="The amount of the deduction line"
    )
    subject_to_tax: Optional[StrictBool] = Field(
        default=None, alias="subjectToTax", description="Identifies if the deduction is subject to tax"
    )
    percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Deduction rate percentage")
    __properties = ["deductionTypeID", "amount", "subjectToTax", "percentage"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeductionLine:
        """Create an instance of DeductionLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeductionLine:
        """Create an instance of DeductionLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DeductionLine.parse_obj(obj)

        _obj = DeductionLine.parse_obj(
            {
                "deduction_type_id": obj.get("deductionTypeID"),
                "amount": obj.get("amount"),
                "subject_to_tax": obj.get("subjectToTax"),
                "percentage": obj.get("percentage"),
            }
        )
        return _obj
