"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, validator


class Deduction(BaseModel):
    """
    Deduction
    """

    deduction_id: Optional[StrictStr] = Field(
        default=None, alias="deductionId", description="The Xero identifier for Deduction"
    )
    deduction_name: StrictStr = Field(default=..., alias="deductionName", description="Name of the deduction")
    deduction_category: Optional[StrictStr] = Field(
        default=None, alias="deductionCategory", description="Deduction Category type"
    )
    liability_account_id: StrictStr = Field(
        default=..., alias="liabilityAccountId", description="Xero identifier for Liability Account"
    )
    current_record: Optional[StrictBool] = Field(
        default=None, alias="currentRecord", description="Identifier of a record is active or not."
    )
    standard_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="standardAmount", description="Standard amount of the deduction"
    )
    reduces_super_liability: Optional[StrictBool] = Field(
        default=None, alias="reducesSuperLiability", description="Identifier of reduces super liability"
    )
    reduces_tax_liability: Optional[StrictBool] = Field(
        default=None, alias="reducesTaxLiability", description="Identifier of reduces tax liability"
    )
    calculation_type: Optional[StrictStr] = Field(
        default=None,
        alias="calculationType",
        description="determine the calculation type whether fixed amount or percentage of gross",
    )
    percentage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Percentage of gross")
    subject_to_nic: Optional[StrictBool] = Field(
        default=None, alias="subjectToNIC", description="Identifier of subject To NIC"
    )
    subject_to_tax: Optional[StrictBool] = Field(
        default=None, alias="subjectToTax", description="Identifier of subject To Tax"
    )
    is_reduced_by_basic_rate: Optional[StrictBool] = Field(
        default=None, alias="isReducedByBasicRate", description="Identifier of reduced by basic rate applicable or not"
    )
    apply_to_pension_calculations: Optional[StrictBool] = Field(
        default=None, alias="applyToPensionCalculations", description="Identifier for apply to pension calculations"
    )
    is_calculating_on_qualifying_earnings: Optional[StrictBool] = Field(
        default=None,
        alias="isCalculatingOnQualifyingEarnings",
        description="Identifier of calculating on qualifying earnings",
    )
    is_pension: Optional[StrictBool] = Field(
        default=None, alias="isPension", description="Identifier of applicable for pension or not"
    )
    __properties = [
        "deductionId",
        "deductionName",
        "deductionCategory",
        "liabilityAccountId",
        "currentRecord",
        "standardAmount",
        "reducesSuperLiability",
        "reducesTaxLiability",
        "calculationType",
        "percentage",
        "subjectToNIC",
        "subjectToTax",
        "isReducedByBasicRate",
        "applyToPensionCalculations",
        "isCalculatingOnQualifyingEarnings",
        "isPension",
    ]

    @validator("deduction_category")
    def deduction_category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "CapitalContributions",
            "ChildCareVoucher",
            "MakingGood",
            "PostgraduateLoanDeductions",
            "PrivateUsePayments",
            "SalarySacrifice",
            "StakeholderPension",
            "StakeholderPensionPostTax",
            "StudentLoanDeductions",
            "UkOther",
        ):
            raise ValueError(
                "must be one of enum values ('CapitalContributions', 'ChildCareVoucher', 'MakingGood', 'PostgraduateLoanDeductions', 'PrivateUsePayments', 'SalarySacrifice', 'StakeholderPension', 'StakeholderPensionPostTax', 'StudentLoanDeductions', 'UkOther')"
            )
        return value

    @validator("calculation_type")
    def calculation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("FixedAmount", "PercentageOfGross"):
            raise ValueError("must be one of enum values ('FixedAmount', 'PercentageOfGross')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Deduction:
        """Create an instance of Deduction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Deduction:
        """Create an instance of Deduction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Deduction.parse_obj(obj)

        _obj = Deduction.parse_obj(
            {
                "deduction_id": obj.get("deductionId"),
                "deduction_name": obj.get("deductionName"),
                "deduction_category": obj.get("deductionCategory"),
                "liability_account_id": obj.get("liabilityAccountId"),
                "current_record": obj.get("currentRecord"),
                "standard_amount": obj.get("standardAmount"),
                "reduces_super_liability": obj.get("reducesSuperLiability"),
                "reduces_tax_liability": obj.get("reducesTaxLiability"),
                "calculation_type": obj.get("calculationType"),
                "percentage": obj.get("percentage"),
                "subject_to_nic": obj.get("subjectToNIC"),
                "subject_to_tax": obj.get("subjectToTax"),
                "is_reduced_by_basic_rate": obj.get("isReducedByBasicRate"),
                "apply_to_pension_calculations": obj.get("applyToPensionCalculations"),
                "is_calculating_on_qualifying_earnings": obj.get("isCalculatingOnQualifyingEarnings"),
                "is_pension": obj.get("isPension"),
            }
        )
        return _obj
