"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr


class EarningsTemplate(BaseModel):
    """
    EarningsTemplate
    """

    pay_template_earning_id: Optional[StrictStr] = Field(
        default=None, alias="payTemplateEarningID", description="The Xero identifier for the earnings template"
    )
    rate_per_unit: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="ratePerUnit", description="The rate per unit"
    )
    number_of_units: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="numberOfUnits", description="The rate per unit"
    )
    fixed_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="fixedAmount", description="The fixed amount per period"
    )
    earnings_rate_id: Optional[StrictStr] = Field(
        default=None, alias="earningsRateID", description="The corresponding earnings rate identifier"
    )
    name: Optional[StrictStr] = Field(default=None, description="The read-only name of the Earning Template.")
    __properties = ["payTemplateEarningID", "ratePerUnit", "numberOfUnits", "fixedAmount", "earningsRateID", "name"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EarningsTemplate:
        """Create an instance of EarningsTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EarningsTemplate:
        """Create an instance of EarningsTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EarningsTemplate.parse_obj(obj)

        _obj = EarningsTemplate.parse_obj(
            {
                "pay_template_earning_id": obj.get("payTemplateEarningID"),
                "rate_per_unit": obj.get("ratePerUnit"),
                "number_of_units": obj.get("numberOfUnits"),
                "fixed_amount": obj.get("fixedAmount"),
                "earnings_rate_id": obj.get("earningsRateID"),
                "name": obj.get("name"),
            }
        )
        return _obj
