"""
merged spec

merged spec

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import json
import re  # noqa: F401

from aenum import Enum


class EarningsType(str, Enum):
    """
    EarningsType
    """

    """
    allowed enum values
    """
    FIXED = "FIXED"
    ORDINARYTIMEEARNINGS = "ORDINARYTIMEEARNINGS"
    OVERTIMEEARNINGS = "OVERTIMEEARNINGS"
    ALLOWANCE = "ALLOWANCE"
    LUMPSUMD = "LUMPSUMD"
    EMPLOYMENTTERMINATIONPAYMENT = "EMPLOYMENTTERMINATIONPAYMENT"
    LUMPSUMA = "LUMPSUMA"
    LUMPSUMB = "LUMPSUMB"
    BONUSESANDCOMMISSIONS = "BONUSESANDCOMMISSIONS"
    LUMPSUME = "LUMPSUME"
    LUMPSUMW = "LUMPSUMW"
    DIRECTORSFEES = "DIRECTORSFEES"
    PAIDPARENTALLEAVE = "PAIDPARENTALLEAVE"
    WORKERSCOMPENSATION = "WORKERSCOMPENSATION"

    @classmethod
    def from_json(cls, json_str: str) -> "EarningsType":
        """Create an instance of EarningsType from a JSON string"""
        return EarningsType(json.loads(json_str))
