"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr


class EarningsLine(BaseModel):
    """
    EarningsLine
    """

    earnings_line_id: Optional[StrictStr] = Field(
        default=None, alias="earningsLineID", description="Xero identifier for payroll earnings line"
    )
    earnings_rate_id: Optional[StrictStr] = Field(
        default=None, alias="earningsRateID", description="Xero identifier for payroll earnings rate"
    )
    display_name: Optional[StrictStr] = Field(
        default=None, alias="displayName", description="name of earnings rate for display in UI"
    )
    rate_per_unit: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="ratePerUnit", description="Rate per unit for earnings line"
    )
    number_of_units: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="numberOfUnits", description="Earnings number of units"
    )
    fixed_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="fixedAmount",
        description="Earnings fixed amount. Only applicable if the EarningsRate RateType is Fixed",
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="The amount of the earnings line."
    )
    is_linked_to_timesheet: Optional[StrictBool] = Field(
        default=None,
        alias="isLinkedToTimesheet",
        description="Identifies if the earnings is taken from the timesheet. False for earnings line",
    )
    is_average_daily_pay_rate: Optional[StrictBool] = Field(
        default=None,
        alias="isAverageDailyPayRate",
        description="Identifies if the earnings is using an average daily pay rate",
    )
    __properties = [
        "earningsLineID",
        "earningsRateID",
        "displayName",
        "ratePerUnit",
        "numberOfUnits",
        "fixedAmount",
        "amount",
        "isLinkedToTimesheet",
        "isAverageDailyPayRate",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EarningsLine:
        """Create an instance of EarningsLine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EarningsLine:
        """Create an instance of EarningsLine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EarningsLine.parse_obj(obj)

        _obj = EarningsLine.parse_obj(
            {
                "earnings_line_id": obj.get("earningsLineID"),
                "earnings_rate_id": obj.get("earningsRateID"),
                "display_name": obj.get("displayName"),
                "rate_per_unit": obj.get("ratePerUnit"),
                "number_of_units": obj.get("numberOfUnits"),
                "fixed_amount": obj.get("fixedAmount"),
                "amount": obj.get("amount"),
                "is_linked_to_timesheet": obj.get("isLinkedToTimesheet"),
                "is_average_daily_pay_rate": obj.get("isAverageDailyPayRate"),
            }
        )
        return _obj
