"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr


class EmployeeTax(BaseModel):
    """
    EmployeeTax
    """

    starter_type: Optional[StrictStr] = Field(default=None, alias="starterType", description="The Starter type.")
    starter_declaration: Optional[StrictStr] = Field(
        default=None, alias="starterDeclaration", description="Starter declaration."
    )
    tax_code: Optional[StrictStr] = Field(default=None, alias="taxCode", description="The Tax code.")
    w1_m1: Optional[StrictBool] = Field(
        default=None, alias="w1M1", description="Describes whether the tax settings is W1M1"
    )
    previous_taxable_pay: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="previousTaxablePay", description="The previous taxable pay"
    )
    previous_tax_paid: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="previousTaxPaid", description="The tax amount previously paid"
    )
    student_loan_deduction: Optional[StrictStr] = Field(
        default=None, alias="studentLoanDeduction", description="The employee's student loan deduction type"
    )
    has_post_graduate_loans: Optional[StrictBool] = Field(
        default=None, alias="hasPostGraduateLoans", description="Describes whether the employee has post graduate loans"
    )
    is_director: Optional[StrictBool] = Field(
        default=None, alias="isDirector", description="Describes whether the employee is director"
    )
    directorship_start_date: Optional[date] = Field(
        default=None, alias="directorshipStartDate", description="The directorship start date"
    )
    nic_calculation_method: Optional[StrictStr] = Field(
        default=None, alias="nicCalculationMethod", description="NICs calculation method"
    )
    __properties = [
        "starterType",
        "starterDeclaration",
        "taxCode",
        "w1M1",
        "previousTaxablePay",
        "previousTaxPaid",
        "studentLoanDeduction",
        "hasPostGraduateLoans",
        "isDirector",
        "directorshipStartDate",
        "nicCalculationMethod",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EmployeeTax:
        """Create an instance of EmployeeTax from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EmployeeTax:
        """Create an instance of EmployeeTax from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EmployeeTax.parse_obj(obj)

        _obj = EmployeeTax.parse_obj(
            {
                "starter_type": obj.get("starterType"),
                "starter_declaration": obj.get("starterDeclaration"),
                "tax_code": obj.get("taxCode"),
                "w1_m1": obj.get("w1M1"),
                "previous_taxable_pay": obj.get("previousTaxablePay"),
                "previous_tax_paid": obj.get("previousTaxPaid"),
                "student_loan_deduction": obj.get("studentLoanDeduction"),
                "has_post_graduate_loans": obj.get("hasPostGraduateLoans"),
                "is_director": obj.get("isDirector"),
                "directorship_start_date": obj.get("directorshipStartDate"),
                "nic_calculation_method": obj.get("nicCalculationMethod"),
            }
        )
        return _obj
