"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, validator


class EmployeeLeaveType(BaseModel):
    """
    EmployeeLeaveType
    """

    leave_type_id: StrictStr = Field(default=..., alias="leaveTypeID", description="The Xero identifier for leave type")
    schedule_of_accrual: StrictStr = Field(
        default=..., alias="scheduleOfAccrual", description="The schedule of accrual"
    )
    hours_accrued_annually: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="hoursAccruedAnnually",
        description='The number of hours accrued for the leave annually. This is 0 when the scheduleOfAccrual chosen is "OnHourWorked"',
    )
    maximum_to_accrue: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="maximumToAccrue",
        description="The maximum number of hours that can be accrued for the leave",
    )
    opening_balance: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="openingBalance",
        description="The initial number of hours assigned when the leave was added to the employee",
    )
    rate_accrued_hourly: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="rateAccruedHourly",
        description='The number of hours added to the leave balance for every hour worked by the employee. This is normally 0, unless the scheduleOfAccrual chosen is "OnHourWorked"',
    )
    schedule_of_accrual_date: Optional[date] = Field(
        default=None,
        alias="scheduleOfAccrualDate",
        description='The date when an employee becomes entitled to their accrual. Only applicable when scheduleOfAccrual is "OnAnniversaryDate"',
    )
    __properties = [
        "leaveTypeID",
        "scheduleOfAccrual",
        "hoursAccruedAnnually",
        "maximumToAccrue",
        "openingBalance",
        "rateAccruedHourly",
        "scheduleOfAccrualDate",
    ]

    @validator("schedule_of_accrual")
    def schedule_of_accrual_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ("BeginningOfCalendarYear", "OnAnniversaryDate", "EachPayPeriod", "OnHourWorked"):
            raise ValueError(
                "must be one of enum values ('BeginningOfCalendarYear', 'OnAnniversaryDate', 'EachPayPeriod', 'OnHourWorked')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EmployeeLeaveType:
        """Create an instance of EmployeeLeaveType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EmployeeLeaveType:
        """Create an instance of EmployeeLeaveType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EmployeeLeaveType.parse_obj(obj)

        _obj = EmployeeLeaveType.parse_obj(
            {
                "leave_type_id": obj.get("leaveTypeID"),
                "schedule_of_accrual": obj.get("scheduleOfAccrual"),
                "hours_accrued_annually": obj.get("hoursAccruedAnnually"),
                "maximum_to_accrue": obj.get("maximumToAccrue"),
                "opening_balance": obj.get("openingBalance"),
                "rate_accrued_hourly": obj.get("rateAccruedHourly"),
                "schedule_of_accrual_date": obj.get("scheduleOfAccrualDate"),
            }
        )
        return _obj
