"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional

from pydantic import BaseModel, Field, StrictBool, StrictStr, validator


class EmployeeStatutoryLeaveSummary(BaseModel):
    """
    EmployeeStatutoryLeaveSummary
    """

    statutory_leave_id: Optional[StrictStr] = Field(
        default=None, alias="statutoryLeaveID", description="The unique identifier (guid) of a statutory leave."
    )
    employee_id: Optional[StrictStr] = Field(
        default=None, alias="employeeID", description="The unique identifier (guid) of the employee"
    )
    type: Optional[StrictStr] = Field(default=None, description="The category of statutory leave")
    start_date: Optional[date] = Field(default=None, alias="startDate", description="The date when the leave starts")
    end_date: Optional[date] = Field(default=None, alias="endDate", description="The date when the leave ends")
    is_entitled: Optional[StrictBool] = Field(
        default=None, alias="isEntitled", description="Whether the leave was entitled to receive payment"
    )
    status: Optional[StrictStr] = Field(default=None, description="The status of the leave")
    __properties = ["statutoryLeaveID", "employeeID", "type", "startDate", "endDate", "isEntitled", "status"]

    @validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("Sick", "Adoption", "Maternity", "Paternity", "Sharedparental"):
            raise ValueError(
                "must be one of enum values ('Sick', 'Adoption', 'Maternity', 'Paternity', 'Sharedparental')"
            )
        return value

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("Pending", "In-Progress", "Completed"):
            raise ValueError("must be one of enum values ('Pending', 'In-Progress', 'Completed')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EmployeeStatutoryLeaveSummary:
        """Create an instance of EmployeeStatutoryLeaveSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EmployeeStatutoryLeaveSummary:
        """Create an instance of EmployeeStatutoryLeaveSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EmployeeStatutoryLeaveSummary.parse_obj(obj)

        _obj = EmployeeStatutoryLeaveSummary.parse_obj(
            {
                "statutory_leave_id": obj.get("statutoryLeaveID"),
                "employee_id": obj.get("employeeID"),
                "type": obj.get("type"),
                "start_date": obj.get("startDate"),
                "end_date": obj.get("endDate"),
                "is_entitled": obj.get("isEntitled"),
                "status": obj.get("status"),
            }
        )
        return _obj
