"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt


class EmployeeOpeningBalance(BaseModel):
    """
    EmployeeOpeningBalance
    """

    period_end_date: Optional[date] = Field(
        default=None, alias="periodEndDate", description="The opening balance period end date."
    )
    days_paid: Optional[StrictInt] = Field(default=None, alias="daysPaid", description="The paid number of days.")
    unpaid_weeks: Optional[StrictInt] = Field(
        default=None, alias="unpaidWeeks", description="The number of unpaid weeks."
    )
    gross_earnings: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="grossEarnings", description="The gross earnings during the period."
    )
    __properties = ["periodEndDate", "daysPaid", "unpaidWeeks", "grossEarnings"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EmployeeOpeningBalance:
        """Create an instance of EmployeeOpeningBalance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EmployeeOpeningBalance:
        """Create an instance of EmployeeOpeningBalance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EmployeeOpeningBalance.parse_obj(obj)

        _obj = EmployeeOpeningBalance.parse_obj(
            {
                "period_end_date": obj.get("periodEndDate"),
                "days_paid": obj.get("daysPaid"),
                "unpaid_weeks": obj.get("unpaidWeeks"),
                "gross_earnings": obj.get("grossEarnings"),
            }
        )
        return _obj
