"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictInt, StrictStr

from xero_python.models.user1 import User1


class FileObject(BaseModel):
    """
    FileObject
    """

    name: Optional[StrictStr] = Field(default=None, alias="Name", description="File Name")
    mime_type: Optional[StrictStr] = Field(
        default=None,
        alias="MimeType",
        description="MimeType of the file (image/png, image/jpeg, application/pdf, etc..)",
    )
    size: Optional[StrictInt] = Field(default=None, alias="Size", description="Numeric value in bytes")
    created_date_utc: Optional[StrictStr] = Field(
        default=None, alias="CreatedDateUtc", description="Created date in UTC"
    )
    updated_date_utc: Optional[StrictStr] = Field(
        default=None, alias="UpdatedDateUtc", description="Updated date in UTC"
    )
    user: Optional[User1] = Field(default=None, alias="User")
    id: Optional[StrictStr] = Field(default=None, alias="Id", description="File object's UUID")
    folder_id: Optional[StrictStr] = Field(default=None, alias="FolderId", description="Folder relation object's UUID")
    __properties = ["Name", "MimeType", "Size", "CreatedDateUtc", "UpdatedDateUtc", "User", "Id", "FolderId"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FileObject:
        """Create an instance of FileObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict["User"] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FileObject:
        """Create an instance of FileObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FileObject.parse_obj(obj)

        _obj = FileObject.parse_obj(
            {
                "name": obj.get("Name"),
                "mime_type": obj.get("MimeType"),
                "size": obj.get("Size"),
                "created_date_utc": obj.get("CreatedDateUtc"),
                "updated_date_utc": obj.get("UpdatedDateUtc"),
                "user": User1.from_dict(obj.get("User")) if obj.get("User") is not None else None,
                "id": obj.get("Id"),
                "folder_id": obj.get("FolderId"),
            }
        )
        return _obj
