"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr


class Folder(BaseModel):
    """
    Folder
    """

    name: Optional[StrictStr] = Field(default=None, alias="Name", description="The name of the folder")
    file_count: Optional[StrictInt] = Field(
        default=None, alias="FileCount", description="The number of files in the folder"
    )
    email: Optional[StrictStr] = Field(
        default=None,
        alias="Email",
        description="The email address used to email files to the inbox. Only the inbox will have this element.",
    )
    is_inbox: Optional[StrictBool] = Field(
        default=None,
        alias="IsInbox",
        description="to indicate if the folder is the Inbox. The Inbox cannot be renamed or deleted.",
    )
    id: Optional[StrictStr] = Field(default=None, alias="Id", description="Xero unique identifier for a folder  Files")
    __properties = ["Name", "FileCount", "Email", "IsInbox", "Id"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Folder:
        """Create an instance of Folder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Folder:
        """Create an instance of Folder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Folder.parse_obj(obj)

        _obj = Folder.parse_obj(
            {
                "name": obj.get("Name"),
                "file_count": obj.get("FileCount"),
                "email": obj.get("Email"),
                "is_inbox": obj.get("IsInbox"),
                "id": obj.get("Id"),
            }
        )
        return _obj
