"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist

from xero_python.models.contact_response import ContactResponse
from xero_python.models.line_item_response import LineItemResponse


class InvoiceResponse(BaseModel):
    """
    InvoiceResponse
    """

    invoice_id: Optional[StrictStr] = Field(default=None, alias="invoiceId", description="Xero Identifier of invoice")
    contact: Optional[ContactResponse] = None
    total: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total of Invoice tax inclusive (i.e. SubTotal + TotalTax); Not included in summary mode",
    )
    line_items: Optional[conlist(LineItemResponse)] = Field(
        default=None, alias="lineItems", description="Not included in summary mode"
    )
    __properties = ["invoiceId", "contact", "total", "lineItems"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InvoiceResponse:
        """Create an instance of InvoiceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of contact
        if self.contact:
            _dict["contact"] = self.contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item in self.line_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict["lineItems"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InvoiceResponse:
        """Create an instance of InvoiceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InvoiceResponse.parse_obj(obj)

        _obj = InvoiceResponse.parse_obj(
            {
                "invoice_id": obj.get("invoiceId"),
                "contact": ContactResponse.from_dict(obj.get("contact")) if obj.get("contact") is not None else None,
                "total": obj.get("total"),
                "line_items": [LineItemResponse.from_dict(_item) for _item in obj.get("lineItems")]
                if obj.get("lineItems") is not None
                else None,
            }
        )
        return _obj
