"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr


class LeaveAccrualLine1(BaseModel):
    """
    LeaveAccrualLine1
    """

    leave_type_id: Optional[StrictStr] = Field(
        default=None, alias="LeaveTypeID", description="Xero identifier for the Leave type."
    )
    number_of_units: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="NumberOfUnits", description="Leave Accrual number of units"
    )
    auto_calculate: Optional[StrictBool] = Field(
        default=None, alias="AutoCalculate", description="If you want to auto calculate leave."
    )
    __properties = ["LeaveTypeID", "NumberOfUnits", "AutoCalculate"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LeaveAccrualLine1:
        """Create an instance of LeaveAccrualLine1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LeaveAccrualLine1:
        """Create an instance of LeaveAccrualLine1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LeaveAccrualLine1.parse_obj(obj)

        _obj = LeaveAccrualLine1.parse_obj(
            {
                "leave_type_id": obj.get("LeaveTypeID"),
                "number_of_units": obj.get("NumberOfUnits"),
                "auto_calculate": obj.get("AutoCalculate"),
            }
        )
        return _obj
