"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, StrictBool, StrictStr


class LeaveType1(BaseModel):
    """
    LeaveType1
    """

    leave_id: Optional[StrictStr] = Field(
        default=None, alias="leaveID", description="Xero unique identifier for the leave"
    )
    leave_type_id: Optional[StrictStr] = Field(
        default=None, alias="leaveTypeID", description="Xero unique identifier for the leave type"
    )
    name: StrictStr = Field(default=..., description="Name of the leave type")
    is_paid_leave: StrictBool = Field(
        default=...,
        alias="isPaidLeave",
        description="Indicate that an employee will be paid when taking this type of leave",
    )
    show_on_payslip: StrictBool = Field(
        default=...,
        alias="showOnPayslip",
        description="Indicate that a balance for this leave type to be shown on the employee’s payslips",
    )
    updated_date_utc: Optional[datetime] = Field(
        default=None, alias="updatedDateUTC", description="UTC timestamp of last update to the leave type note"
    )
    is_active: Optional[StrictBool] = Field(
        default=None, alias="isActive", description="Shows whether the leave type is active or not"
    )
    is_statutory_leave: Optional[StrictBool] = Field(
        default=None,
        alias="isStatutoryLeave",
        description="Shows whether the leave type is a statutory leave type or not",
    )
    __properties = [
        "leaveID",
        "leaveTypeID",
        "name",
        "isPaidLeave",
        "showOnPayslip",
        "updatedDateUTC",
        "isActive",
        "isStatutoryLeave",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LeaveType1:
        """Create an instance of LeaveType1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LeaveType1:
        """Create an instance of LeaveType1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LeaveType1.parse_obj(obj)

        _obj = LeaveType1.parse_obj(
            {
                "leave_id": obj.get("leaveID"),
                "leave_type_id": obj.get("leaveTypeID"),
                "name": obj.get("name"),
                "is_paid_leave": obj.get("isPaidLeave"),
                "show_on_payslip": obj.get("showOnPayslip"),
                "updated_date_utc": obj.get("updatedDateUTC"),
                "is_active": obj.get("isActive"),
                "is_statutory_leave": obj.get("isStatutoryLeave"),
            }
        )
        return _obj
