"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist, validator

from xero_python.models.validation_error import ValidationError


class LinkedTransaction(BaseModel):
    """
    LinkedTransaction
    """

    source_transaction_id: Optional[StrictStr] = Field(
        default=None,
        alias="SourceTransactionID",
        description="Filter by the SourceTransactionID. Get all the linked transactions created from a particular ACCPAY invoice",
    )
    source_line_item_id: Optional[StrictStr] = Field(
        default=None, alias="SourceLineItemID", description="The line item identifier from the source transaction."
    )
    contact_id: Optional[StrictStr] = Field(
        default=None,
        alias="ContactID",
        description="Filter by the combination of ContactID and Status. Get all the linked transactions that have been assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED.",
    )
    target_transaction_id: Optional[StrictStr] = Field(
        default=None,
        alias="TargetTransactionID",
        description="Filter by the TargetTransactionID. Get all the linked transactions  allocated to a particular ACCREC invoice",
    )
    target_line_item_id: Optional[StrictStr] = Field(
        default=None,
        alias="TargetLineItemID",
        description="The line item identifier from the target transaction. It is possible  to link multiple billable expenses to the same TargetLineItemID.",
    )
    linked_transaction_id: Optional[StrictStr] = Field(
        default=None,
        alias="LinkedTransactionID",
        description="The Xero identifier for an Linked Transaction e.g./LinkedTransactions/297c2dc5-cc47-4afd-8ec8-74990b8761e9",
    )
    status: Optional[StrictStr] = Field(
        default=None,
        alias="Status",
        description="Filter by the combination of ContactID and Status. Get all the linked transactions that have been assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED.",
    )
    type: Optional[StrictStr] = Field(
        default=None,
        alias="Type",
        description="This will always be BILLABLEEXPENSE. More types may be added in future.",
    )
    updated_date_utc: Optional[StrictStr] = Field(
        default=None, alias="UpdatedDateUTC", description="The last modified date in UTC format"
    )
    source_transaction_type_code: Optional[StrictStr] = Field(
        default=None,
        alias="SourceTransactionTypeCode",
        description="The Type of the source tranasction. This will be ACCPAY if the linked transaction was created from an invoice and SPEND if it was created from a bank transaction.",
    )
    validation_errors: Optional[conlist(ValidationError)] = Field(
        default=None, alias="ValidationErrors", description="Displays array of validation error messages from the API"
    )
    __properties = [
        "SourceTransactionID",
        "SourceLineItemID",
        "ContactID",
        "TargetTransactionID",
        "TargetLineItemID",
        "LinkedTransactionID",
        "Status",
        "Type",
        "UpdatedDateUTC",
        "SourceTransactionTypeCode",
        "ValidationErrors",
    ]

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("APPROVED", "DRAFT", "ONDRAFT", "BILLED", "VOIDED"):
            raise ValueError("must be one of enum values ('APPROVED', 'DRAFT', 'ONDRAFT', 'BILLED', 'VOIDED')")
        return value

    @validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("BILLABLEEXPENSE",):
            raise ValueError("must be one of enum values ('BILLABLEEXPENSE')")
        return value

    @validator("source_transaction_type_code")
    def source_transaction_type_code_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("ACCPAY", "SPEND"):
            raise ValueError("must be one of enum values ('ACCPAY', 'SPEND')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LinkedTransaction:
        """Create an instance of LinkedTransaction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={"updated_date_utc"}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in validation_errors (list)
        _items = []
        if self.validation_errors:
            for _item in self.validation_errors:
                if _item:
                    _items.append(_item.to_dict())
            _dict["ValidationErrors"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LinkedTransaction:
        """Create an instance of LinkedTransaction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LinkedTransaction.parse_obj(obj)

        _obj = LinkedTransaction.parse_obj(
            {
                "source_transaction_id": obj.get("SourceTransactionID"),
                "source_line_item_id": obj.get("SourceLineItemID"),
                "contact_id": obj.get("ContactID"),
                "target_transaction_id": obj.get("TargetTransactionID"),
                "target_line_item_id": obj.get("TargetLineItemID"),
                "linked_transaction_id": obj.get("LinkedTransactionID"),
                "status": obj.get("Status"),
                "type": obj.get("Type"),
                "updated_date_utc": obj.get("UpdatedDateUTC"),
                "source_transaction_type_code": obj.get("SourceTransactionTypeCode"),
                "validation_errors": [ValidationError.from_dict(_item) for _item in obj.get("ValidationErrors")]
                if obj.get("ValidationErrors") is not None
                else None,
            }
        )
        return _obj
