"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist

from xero_python.models.lock_history_model import LockHistoryModel


class LockHistoryResponse(BaseModel):
    """
    LockHistoryResponse
    """

    organisation_id: Optional[StrictStr] = Field(
        default=None, alias="organisationId", description="The requested Organisation to which the data pertains"
    )
    end_date: Optional[date] = Field(default=None, alias="endDate", description="The end date of the report")
    lock_dates: Optional[conlist(LockHistoryModel)] = Field(default=None, alias="lockDates")
    __properties = ["organisationId", "endDate", "lockDates"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LockHistoryResponse:
        """Create an instance of LockHistoryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in lock_dates (list)
        _items = []
        if self.lock_dates:
            for _item in self.lock_dates:
                if _item:
                    _items.append(_item.to_dict())
            _dict["lockDates"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LockHistoryResponse:
        """Create an instance of LockHistoryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LockHistoryResponse.parse_obj(obj)

        _obj = LockHistoryResponse.parse_obj(
            {
                "organisation_id": obj.get("organisationId"),
                "end_date": obj.get("endDate"),
                "lock_dates": [LockHistoryModel.from_dict(_item) for _item in obj.get("lockDates")]
                if obj.get("lockDates") is not None
                else None,
            }
        )
        return _obj
