"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist, validator

from xero_python.models.attachment import Attachment
from xero_python.models.manual_journal_line import ManualJournalLine
from xero_python.models.validation_error import ValidationError


class ManualJournal(BaseModel):
    """
    ManualJournal
    """

    narration: StrictStr = Field(default=..., alias="Narration", description="Description of journal being posted")
    journal_lines: Optional[conlist(ManualJournalLine)] = Field(
        default=None, alias="JournalLines", description="See JournalLines"
    )
    var_date: Optional[StrictStr] = Field(
        default=None, alias="Date", description="Date journal was posted – YYYY-MM-DD"
    )
    line_amount_types: Optional[StrictStr] = Field(default=None, alias="LineAmountTypes")
    status: Optional[StrictStr] = Field(default=None, alias="Status", description="See Manual Journal Status Codes")
    url: Optional[StrictStr] = Field(
        default=None,
        alias="Url",
        description="Url link to a source document – shown as “Go to [appName]” in the Xero app",
    )
    show_on_cash_basis_reports: Optional[StrictBool] = Field(
        default=None, alias="ShowOnCashBasisReports", description="Boolean – default is true if not specified"
    )
    has_attachments: Optional[StrictBool] = Field(
        default=False, alias="HasAttachments", description="Boolean to indicate if a manual journal has an attachment"
    )
    updated_date_utc: Optional[StrictStr] = Field(
        default=None, alias="UpdatedDateUTC", description="Last modified date UTC format"
    )
    manual_journal_id: Optional[StrictStr] = Field(
        default=None, alias="ManualJournalID", description="The Xero identifier for a Manual Journal"
    )
    status_attribute_string: Optional[StrictStr] = Field(
        default=None, alias="StatusAttributeString", description="A string to indicate if a invoice status"
    )
    warnings: Optional[conlist(ValidationError)] = Field(
        default=None, alias="Warnings", description="Displays array of warning messages from the API"
    )
    validation_errors: Optional[conlist(ValidationError)] = Field(
        default=None, alias="ValidationErrors", description="Displays array of validation error messages from the API"
    )
    attachments: Optional[conlist(Attachment)] = Field(
        default=None, alias="Attachments", description="Displays array of attachments from the API"
    )
    __properties = [
        "Narration",
        "JournalLines",
        "Date",
        "LineAmountTypes",
        "Status",
        "Url",
        "ShowOnCashBasisReports",
        "HasAttachments",
        "UpdatedDateUTC",
        "ManualJournalID",
        "StatusAttributeString",
        "Warnings",
        "ValidationErrors",
        "Attachments",
    ]

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("DRAFT", "POSTED", "DELETED", "VOIDED", "ARCHIVED"):
            raise ValueError("must be one of enum values ('DRAFT', 'POSTED', 'DELETED', 'VOIDED', 'ARCHIVED')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ManualJournal:
        """Create an instance of ManualJournal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={"has_attachments", "updated_date_utc"}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in journal_lines (list)
        _items = []
        if self.journal_lines:
            for _item in self.journal_lines:
                if _item:
                    _items.append(_item.to_dict())
            _dict["JournalLines"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item in self.warnings:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Warnings"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in validation_errors (list)
        _items = []
        if self.validation_errors:
            for _item in self.validation_errors:
                if _item:
                    _items.append(_item.to_dict())
            _dict["ValidationErrors"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item in self.attachments:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Attachments"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ManualJournal:
        """Create an instance of ManualJournal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ManualJournal.parse_obj(obj)

        _obj = ManualJournal.parse_obj(
            {
                "narration": obj.get("Narration"),
                "journal_lines": [ManualJournalLine.from_dict(_item) for _item in obj.get("JournalLines")]
                if obj.get("JournalLines") is not None
                else None,
                "var_date": obj.get("Date"),
                "line_amount_types": obj.get("LineAmountTypes"),
                "status": obj.get("Status"),
                "url": obj.get("Url"),
                "show_on_cash_basis_reports": obj.get("ShowOnCashBasisReports"),
                "has_attachments": obj.get("HasAttachments") if obj.get("HasAttachments") is not None else False,
                "updated_date_utc": obj.get("UpdatedDateUTC"),
                "manual_journal_id": obj.get("ManualJournalID"),
                "status_attribute_string": obj.get("StatusAttributeString"),
                "warnings": [ValidationError.from_dict(_item) for _item in obj.get("Warnings")]
                if obj.get("Warnings") is not None
                else None,
                "validation_errors": [ValidationError.from_dict(_item) for _item in obj.get("ValidationErrors")]
                if obj.get("ValidationErrors") is not None
                else None,
                "attachments": [Attachment.from_dict(_item) for _item in obj.get("Attachments")]
                if obj.get("Attachments") is not None
                else None,
            }
        )
        return _obj
