"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conlist, validator

from xero_python.models.attachment import Attachment
from xero_python.models.contact import Contact
from xero_python.models.line_item import LineItem


class Overpayment(BaseModel):
    """
    Overpayment
    """

    type: Optional[StrictStr] = Field(default=None, alias="Type", description="See Overpayment Types")
    contact: Optional[Contact] = Field(default=None, alias="Contact")
    var_date: Optional[StrictStr] = Field(
        default=None, alias="Date", description="The date the overpayment is created YYYY-MM-DD"
    )
    status: Optional[StrictStr] = Field(default=None, alias="Status", description="See Overpayment Status Codes")
    line_amount_types: Optional[StrictStr] = Field(default=None, alias="LineAmountTypes")
    line_items: Optional[conlist(LineItem)] = Field(
        default=None, alias="LineItems", description="See Overpayment Line Items"
    )
    sub_total: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="SubTotal", description="The subtotal of the overpayment excluding taxes"
    )
    total_tax: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="TotalTax", description="The total tax on the overpayment"
    )
    total: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="Total", description="The total of the overpayment (subtotal + total tax)"
    )
    updated_date_utc: Optional[StrictStr] = Field(
        default=None, alias="UpdatedDateUTC", description="UTC timestamp of last update to the overpayment"
    )
    currency_code: Optional[StrictStr] = Field(default=None, alias="CurrencyCode")
    overpayment_id: Optional[StrictStr] = Field(
        default=None, alias="OverpaymentID", description="Xero generated unique identifier"
    )
    currency_rate: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="CurrencyRate",
        description="The currency rate for a multicurrency overpayment. If no rate is specified, the XE.com day rate is used",
    )
    remaining_credit: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="RemainingCredit", description="The remaining credit balance on the overpayment"
    )
    allocations: Optional[conlist(Allocation)] = Field(default=None, alias="Allocations", description="See Allocations")
    applied_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="AppliedAmount", description="The amount of applied to an invoice"
    )
    payments: Optional[conlist(Payment)] = Field(default=None, alias="Payments", description="See Payments")
    has_attachments: Optional[StrictBool] = Field(
        default=False, alias="HasAttachments", description="boolean to indicate if a overpayment has an attachment"
    )
    attachments: Optional[conlist(Attachment)] = Field(default=None, alias="Attachments", description="See Attachments")
    __properties = [
        "Type",
        "Contact",
        "Date",
        "Status",
        "LineAmountTypes",
        "LineItems",
        "SubTotal",
        "TotalTax",
        "Total",
        "UpdatedDateUTC",
        "CurrencyCode",
        "OverpaymentID",
        "CurrencyRate",
        "RemainingCredit",
        "Allocations",
        "AppliedAmount",
        "Payments",
        "HasAttachments",
        "Attachments",
    ]

    @validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("RECEIVE-OVERPAYMENT", "SPEND-OVERPAYMENT", "AROVERPAYMENT"):
            raise ValueError("must be one of enum values ('RECEIVE-OVERPAYMENT', 'SPEND-OVERPAYMENT', 'AROVERPAYMENT')")
        return value

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("AUTHORISED", "PAID", "VOIDED"):
            raise ValueError("must be one of enum values ('AUTHORISED', 'PAID', 'VOIDED')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Overpayment:
        """Create an instance of Overpayment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={"updated_date_utc", "has_attachments"}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of contact
        if self.contact:
            _dict["Contact"] = self.contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in line_items (list)
        _items = []
        if self.line_items:
            for _item in self.line_items:
                if _item:
                    _items.append(_item.to_dict())
            _dict["LineItems"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in allocations (list)
        _items = []
        if self.allocations:
            for _item in self.allocations:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Allocations"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payments (list)
        _items = []
        if self.payments:
            for _item in self.payments:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Payments"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item in self.attachments:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Attachments"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Overpayment:
        """Create an instance of Overpayment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Overpayment.parse_obj(obj)

        _obj = Overpayment.parse_obj(
            {
                "type": obj.get("Type"),
                "contact": Contact.from_dict(obj.get("Contact")) if obj.get("Contact") is not None else None,
                "var_date": obj.get("Date"),
                "status": obj.get("Status"),
                "line_amount_types": obj.get("LineAmountTypes"),
                "line_items": [LineItem.from_dict(_item) for _item in obj.get("LineItems")]
                if obj.get("LineItems") is not None
                else None,
                "sub_total": obj.get("SubTotal"),
                "total_tax": obj.get("TotalTax"),
                "total": obj.get("Total"),
                "updated_date_utc": obj.get("UpdatedDateUTC"),
                "currency_code": obj.get("CurrencyCode"),
                "overpayment_id": obj.get("OverpaymentID"),
                "currency_rate": obj.get("CurrencyRate"),
                "remaining_credit": obj.get("RemainingCredit"),
                "allocations": [Allocation.from_dict(_item) for _item in obj.get("Allocations")]
                if obj.get("Allocations") is not None
                else None,
                "applied_amount": obj.get("AppliedAmount"),
                "payments": [Payment.from_dict(_item) for _item in obj.get("Payments")]
                if obj.get("Payments") is not None
                else None,
                "has_attachments": obj.get("HasAttachments") if obj.get("HasAttachments") is not None else False,
                "attachments": [Attachment.from_dict(_item) for _item in obj.get("Attachments")]
                if obj.get("Attachments") is not None
                else None,
            }
        )
        return _obj


from xero_python.models.allocation import Allocation
from xero_python.models.payment import Payment

Overpayment.update_forward_refs()
