"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist, validator

from xero_python.models.payslip import Payslip


class PayRun(BaseModel):
    """
    PayRun
    """

    pay_run_id: Optional[StrictStr] = Field(
        default=None, alias="payRunID", description="Xero unique identifier for the pay run"
    )
    payroll_calendar_id: Optional[StrictStr] = Field(
        default=None, alias="payrollCalendarID", description="Xero unique identifier for the payroll calendar"
    )
    period_start_date: Optional[date] = Field(
        default=None, alias="periodStartDate", description="Period start date of the payroll calendar"
    )
    period_end_date: Optional[date] = Field(
        default=None, alias="periodEndDate", description="Period end date of the payroll calendar"
    )
    payment_date: Optional[date] = Field(default=None, alias="paymentDate", description="Payment date of the pay run")
    total_cost: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="totalCost", description="Total cost of the pay run"
    )
    total_pay: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="totalPay", description="Total pay of the pay run"
    )
    pay_run_status: Optional[StrictStr] = Field(default=None, alias="payRunStatus", description="Pay run status")
    pay_run_type: Optional[StrictStr] = Field(default=None, alias="payRunType", description="Pay run type")
    calendar_type: Optional[StrictStr] = Field(
        default=None, alias="calendarType", description="Calendar type of the pay run"
    )
    posted_date_time: Optional[date] = Field(
        default=None, alias="postedDateTime", description="Posted date time of the pay run"
    )
    pay_slips: Optional[conlist(Payslip)] = Field(default=None, alias="paySlips")
    __properties = [
        "payRunID",
        "payrollCalendarID",
        "periodStartDate",
        "periodEndDate",
        "paymentDate",
        "totalCost",
        "totalPay",
        "payRunStatus",
        "payRunType",
        "calendarType",
        "postedDateTime",
        "paySlips",
    ]

    @validator("pay_run_status")
    def pay_run_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("Draft", "Posted"):
            raise ValueError("must be one of enum values ('Draft', 'Posted')")
        return value

    @validator("pay_run_type")
    def pay_run_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("Scheduled", "Unscheduled", "EarlierYearUpdate"):
            raise ValueError("must be one of enum values ('Scheduled', 'Unscheduled', 'EarlierYearUpdate')")
        return value

    @validator("calendar_type")
    def calendar_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("Weekly", "Fortnightly", "FourWeekly", "Monthly", "Annual", "Quarterly"):
            raise ValueError(
                "must be one of enum values ('Weekly', 'Fortnightly', 'FourWeekly', 'Monthly', 'Annual', 'Quarterly')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PayRun:
        """Create an instance of PayRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in pay_slips (list)
        _items = []
        if self.pay_slips:
            for _item in self.pay_slips:
                if _item:
                    _items.append(_item.to_dict())
            _dict["paySlips"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PayRun:
        """Create an instance of PayRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PayRun.parse_obj(obj)

        _obj = PayRun.parse_obj(
            {
                "pay_run_id": obj.get("payRunID"),
                "payroll_calendar_id": obj.get("payrollCalendarID"),
                "period_start_date": obj.get("periodStartDate"),
                "period_end_date": obj.get("periodEndDate"),
                "payment_date": obj.get("paymentDate"),
                "total_cost": obj.get("totalCost"),
                "total_pay": obj.get("totalPay"),
                "pay_run_status": obj.get("payRunStatus"),
                "pay_run_type": obj.get("payRunType"),
                "calendar_type": obj.get("calendarType"),
                "posted_date_time": obj.get("postedDateTime"),
                "pay_slips": [Payslip.from_dict(_item) for _item in obj.get("paySlips")]
                if obj.get("paySlips") is not None
                else None,
            }
        )
        return _obj
