"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, conlist

from xero_python.models.pagination1 import Pagination1
from xero_python.models.payment import Payment
from xero_python.models.validation_error import ValidationError


class Payments(BaseModel):
    """
    Payments
    """

    pagination: Optional[Pagination1] = None
    warnings: Optional[conlist(ValidationError)] = Field(
        default=None, alias="Warnings", description="Displays array of warning messages from the API"
    )
    payments: Optional[conlist(Payment)] = Field(default=None, alias="Payments")
    __properties = ["pagination", "Warnings", "Payments"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Payments:
        """Create an instance of Payments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of pagination
        if self.pagination:
            _dict["pagination"] = self.pagination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item in self.warnings:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Warnings"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payments (list)
        _items = []
        if self.payments:
            for _item in self.payments:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Payments"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Payments:
        """Create an instance of Payments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Payments.parse_obj(obj)

        _obj = Payments.parse_obj(
            {
                "pagination": Pagination1.from_dict(obj.get("pagination"))
                if obj.get("pagination") is not None
                else None,
                "warnings": [ValidationError.from_dict(_item) for _item in obj.get("Warnings")]
                if obj.get("Warnings") is not None
                else None,
                "payments": [Payment.from_dict(_item) for _item in obj.get("Payments")]
                if obj.get("Payments") is not None
                else None,
            }
        )
        return _obj
