"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

from xero_python.models.credit_note_response import CreditNoteResponse
from xero_python.models.invoice_response import InvoiceResponse
from xero_python.models.overpayment_response import OverpaymentResponse
from xero_python.models.prepayment_response import PrepaymentResponse


class PaymentResponse(BaseModel):
    """
    PaymentResponse
    """

    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId", description="Xero Identifier of payment")
    batch_payment_id: Optional[StrictStr] = Field(
        default=None,
        alias="batchPaymentId",
        description="Xero Identifier of batch payment. Present if the payment was created as part of a batch.",
    )
    var_date: Optional[date] = Field(
        default=None, alias="date", description="Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06"
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The amount of the payment")
    bank_amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="bankAmount", description="The bank amount of the payment"
    )
    currency_rate: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        alias="currencyRate",
        description="Exchange rate when payment is received. Only used for non base currency invoices and credit notes e.g. 0.7500",
    )
    invoice: Optional[InvoiceResponse] = None
    credit_note: Optional[CreditNoteResponse] = Field(default=None, alias="creditNote")
    prepayment: Optional[PrepaymentResponse] = None
    overpayment: Optional[OverpaymentResponse] = None
    __properties = [
        "paymentId",
        "batchPaymentId",
        "date",
        "amount",
        "bankAmount",
        "currencyRate",
        "invoice",
        "creditNote",
        "prepayment",
        "overpayment",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PaymentResponse:
        """Create an instance of PaymentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of invoice
        if self.invoice:
            _dict["invoice"] = self.invoice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credit_note
        if self.credit_note:
            _dict["creditNote"] = self.credit_note.to_dict()
        # override the default output from pydantic by calling `to_dict()` of prepayment
        if self.prepayment:
            _dict["prepayment"] = self.prepayment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of overpayment
        if self.overpayment:
            _dict["overpayment"] = self.overpayment.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PaymentResponse:
        """Create an instance of PaymentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PaymentResponse.parse_obj(obj)

        _obj = PaymentResponse.parse_obj(
            {
                "payment_id": obj.get("paymentId"),
                "batch_payment_id": obj.get("batchPaymentId"),
                "var_date": obj.get("date"),
                "amount": obj.get("amount"),
                "bank_amount": obj.get("bankAmount"),
                "currency_rate": obj.get("currencyRate"),
                "invoice": InvoiceResponse.from_dict(obj.get("invoice")) if obj.get("invoice") is not None else None,
                "credit_note": CreditNoteResponse.from_dict(obj.get("creditNote"))
                if obj.get("creditNote") is not None
                else None,
                "prepayment": PrepaymentResponse.from_dict(obj.get("prepayment"))
                if obj.get("prepayment") is not None
                else None,
                "overpayment": OverpaymentResponse.from_dict(obj.get("overpayment"))
                if obj.get("overpayment") is not None
                else None,
            }
        )
        return _obj
