"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, conlist

from xero_python.models.calendar_type1 import CalendarType1
from xero_python.models.validation_error import ValidationError


class PayrollCalendar(BaseModel):
    """
    PayrollCalendar
    """

    name: Optional[StrictStr] = Field(default=None, alias="Name", description="Name of the Payroll Calendar")
    calendar_type: Optional[CalendarType1] = Field(default=None, alias="CalendarType")
    start_date: Optional[StrictStr] = Field(
        default=None,
        alias="StartDate",
        description="The start date of the upcoming pay period. The end date will be calculated based upon this date, and the calendar type selected (YYYY-MM-DD)",
    )
    payment_date: Optional[StrictStr] = Field(
        default=None,
        alias="PaymentDate",
        description="The date on which employees will be paid for the upcoming pay period (YYYY-MM-DD)",
    )
    payroll_calendar_id: Optional[StrictStr] = Field(
        default=None, alias="PayrollCalendarID", description="Xero identifier"
    )
    updated_date_utc: Optional[StrictStr] = Field(
        default=None, alias="UpdatedDateUTC", description="Last modified timestamp"
    )
    reference_date: Optional[StrictStr] = Field(
        default=None, alias="ReferenceDate", description="Reference Date (YYYY-MM-DD)"
    )
    validation_errors: Optional[conlist(ValidationError)] = Field(
        default=None, alias="ValidationErrors", description="Displays array of validation error messages from the API"
    )
    __properties = [
        "Name",
        "CalendarType",
        "StartDate",
        "PaymentDate",
        "PayrollCalendarID",
        "UpdatedDateUTC",
        "ReferenceDate",
        "ValidationErrors",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PayrollCalendar:
        """Create an instance of PayrollCalendar from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={"updated_date_utc"}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in validation_errors (list)
        _items = []
        if self.validation_errors:
            for _item in self.validation_errors:
                if _item:
                    _items.append(_item.to_dict())
            _dict["ValidationErrors"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PayrollCalendar:
        """Create an instance of PayrollCalendar from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PayrollCalendar.parse_obj(obj)

        _obj = PayrollCalendar.parse_obj(
            {
                "name": obj.get("Name"),
                "calendar_type": obj.get("CalendarType"),
                "start_date": obj.get("StartDate"),
                "payment_date": obj.get("PaymentDate"),
                "payroll_calendar_id": obj.get("PayrollCalendarID"),
                "updated_date_utc": obj.get("UpdatedDateUTC"),
                "reference_date": obj.get("ReferenceDate"),
                "validation_errors": [ValidationError.from_dict(_item) for _item in obj.get("ValidationErrors")]
                if obj.get("ValidationErrors") is not None
                else None,
            }
        )
        return _obj
