"""
merged spec

merged spec

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import json
import re  # noqa: F401

from aenum import Enum


class ProblemType(str, Enum):
    """
    ProblemType
    """

    """
    allowed enum values
    """
    NOTSET = "NotSet"
    BANK_MINUS_ACCOUNT_MINUS_NOT_MINUS_FOUND = "bank-account-not-found"
    INTERNAL_MINUS_ERROR = "internal-error"
    INVALID_MINUS_APPLICATION = "invalid-application"
    INVALID_MINUS_REQUEST = "invalid-request"
    ORGANISATION_MINUS_NOT_MINUS_FOUND = "organisation-not-found"
    ORGANISATION_MINUS_OFFLINE = "organisation-offline"
    REQUEST_MINUS_TIMEOUT = "request-timeout"
    SERVICE_MINUS_UNAVAILABLE = "service-unavailable"
    UNAUTHORIZED = "unauthorized"
    RATE_MINUS_LIMIT_MINUS_ERROR = "rate-limit-error"

    @classmethod
    def from_json(cls, json_str: str) -> "ProblemType":
        """Create an instance of ProblemType from a JSON string"""
        return ProblemType(json.loads(json_str))
