"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictBool, StrictStr


class Reimbursement(BaseModel):
    """
    Reimbursement
    """

    reimbursement_id: Optional[StrictStr] = Field(
        default=None, alias="reimbursementID", description="Xero unique identifier for a reimbursement"
    )
    name: StrictStr = Field(default=..., description="Name of the reimbursement")
    account_id: StrictStr = Field(
        default=..., alias="accountID", description="Xero unique identifier for the account used for the reimbursement"
    )
    current_record: Optional[StrictBool] = Field(
        default=None, alias="currentRecord", description="Indicates that whether the reimbursement is active"
    )
    __properties = ["reimbursementID", "name", "accountID", "currentRecord"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Reimbursement:
        """Create an instance of Reimbursement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Reimbursement:
        """Create an instance of Reimbursement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Reimbursement.parse_obj(obj)

        _obj = Reimbursement.parse_obj(
            {
                "reimbursement_id": obj.get("reimbursementID"),
                "name": obj.get("name"),
                "account_id": obj.get("accountID"),
                "current_record": obj.get("currentRecord"),
            }
        )
        return _obj
