"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, conlist

from xero_python.models.account import Account
from xero_python.models.conversion_balances import ConversionBalances
from xero_python.models.conversion_date import ConversionDate


class Setup(BaseModel):
    """
    Setup
    """

    conversion_date: Optional[ConversionDate] = Field(default=None, alias="ConversionDate")
    conversion_balances: Optional[conlist(ConversionBalances)] = Field(
        default=None,
        alias="ConversionBalances",
        description="Balance supplied for each account that has a value as at the conversion date.",
    )
    accounts: Optional[conlist(Account)] = Field(default=None, alias="Accounts")
    __properties = ["ConversionDate", "ConversionBalances", "Accounts"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Setup:
        """Create an instance of Setup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of conversion_date
        if self.conversion_date:
            _dict["ConversionDate"] = self.conversion_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in conversion_balances (list)
        _items = []
        if self.conversion_balances:
            for _item in self.conversion_balances:
                if _item:
                    _items.append(_item.to_dict())
            _dict["ConversionBalances"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item in self.accounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict["Accounts"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Setup:
        """Create an instance of Setup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Setup.parse_obj(obj)

        _obj = Setup.parse_obj(
            {
                "conversion_date": ConversionDate.from_dict(obj.get("ConversionDate"))
                if obj.get("ConversionDate") is not None
                else None,
                "conversion_balances": [ConversionBalances.from_dict(_item) for _item in obj.get("ConversionBalances")]
                if obj.get("ConversionBalances") is not None
                else None,
                "accounts": [Account.from_dict(_item) for _item in obj.get("Accounts")]
                if obj.get("Accounts") is not None
                else None,
            }
        )
        return _obj
