"""
merged spec

merged spec

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import json
import re  # noqa: F401

from aenum import Enum


class StatutoryDeductionCategory1(str, Enum):
    """
    Statutory Deduction Category
    """

    """
    allowed enum values
    """
    ADDITIONALSTUDENTLOAN = "AdditionalStudentLoan"
    CHILDSUPPORT = "ChildSupport"
    COURTFINES = "CourtFines"
    CREDITOR = "Creditor"
    FEDERALLEVY = "FederalLevy"
    INLANDREVENUEARREARS = "InlandRevenueArrears"
    KIWISAVER = "KiwiSaver"
    MSDREPAYMENTS = "MsdRepayments"
    NONPRIORITYORDER = "NonPriorityOrder"
    PRIORITYORDER = "PriorityOrder"
    TABLEBASED = "TableBased"
    STUDENTLOAN = "StudentLoan"
    VOLUNTARYSTUDENTLOAN = "VoluntaryStudentLoan"
    USCHILDSUPPORT = "USChildSupport"

    @classmethod
    def from_json(cls, json_str: str) -> "StatutoryDeductionCategory1":
        """Create an instance of StatutoryDeductionCategory1 from a JSON string"""
        return StatutoryDeductionCategory1(json.loads(json_str))
