"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr, conlist

from xero_python.models.bank_transaction_response import BankTransactionResponse
from xero_python.models.payment_response import PaymentResponse


class StatementLineResponse(BaseModel):
    """
    StatementLineResponse
    """

    statement_line_id: Optional[StrictStr] = Field(
        default=None, alias="statementLineId", description="Xero Identifier of statement line"
    )
    posted_date: Optional[date] = Field(
        default=None, alias="postedDate", description="Date of when statement line was posted"
    )
    payee: Optional[StrictStr] = Field(default=None, description="Payee description of statement line")
    reference: Optional[StrictStr] = Field(default=None, description="Reference description of statement line")
    notes: Optional[StrictStr] = Field(default=None, description="Notes description of statement line")
    cheque_no: Optional[StrictStr] = Field(
        default=None, alias="chequeNo", description="Cheque number of statement line"
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount of statement line")
    transaction_date: Optional[date] = Field(
        default=None, alias="transactionDate", description="Transaction date of statement line"
    )
    type: Optional[StrictStr] = Field(default=None, description="Type of statement line")
    is_reconciled: Optional[StrictBool] = Field(
        default=None, alias="isReconciled", description="Boolean to show if statement line is reconciled"
    )
    is_duplicate: Optional[StrictBool] = Field(
        default=None, alias="isDuplicate", description="Boolean to show if statement line is duplicate"
    )
    is_deleted: Optional[StrictBool] = Field(
        default=None, alias="isDeleted", description="Boolean to show if statement line is deleted"
    )
    payments: Optional[conlist(PaymentResponse)] = Field(
        default=None, description="List of payments associated with reconciled statement lines"
    )
    bank_transactions: Optional[conlist(BankTransactionResponse)] = Field(
        default=None,
        alias="bankTransactions",
        description="List of bank transactions associated with reconciled statement lines",
    )
    __properties = [
        "statementLineId",
        "postedDate",
        "payee",
        "reference",
        "notes",
        "chequeNo",
        "amount",
        "transactionDate",
        "type",
        "isReconciled",
        "isDuplicate",
        "isDeleted",
        "payments",
        "bankTransactions",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StatementLineResponse:
        """Create an instance of StatementLineResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in payments (list)
        _items = []
        if self.payments:
            for _item in self.payments:
                if _item:
                    _items.append(_item.to_dict())
            _dict["payments"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bank_transactions (list)
        _items = []
        if self.bank_transactions:
            for _item in self.bank_transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["bankTransactions"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StatementLineResponse:
        """Create an instance of StatementLineResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StatementLineResponse.parse_obj(obj)

        _obj = StatementLineResponse.parse_obj(
            {
                "statement_line_id": obj.get("statementLineId"),
                "posted_date": obj.get("postedDate"),
                "payee": obj.get("payee"),
                "reference": obj.get("reference"),
                "notes": obj.get("notes"),
                "cheque_no": obj.get("chequeNo"),
                "amount": obj.get("amount"),
                "transaction_date": obj.get("transactionDate"),
                "type": obj.get("type"),
                "is_reconciled": obj.get("isReconciled"),
                "is_duplicate": obj.get("isDuplicate"),
                "is_deleted": obj.get("isDeleted"),
                "payments": [PaymentResponse.from_dict(_item) for _item in obj.get("payments")]
                if obj.get("payments") is not None
                else None,
                "bank_transactions": [BankTransactionResponse.from_dict(_item) for _item in obj.get("bankTransactions")]
                if obj.get("bankTransactions") is not None
                else None,
            }
        )
        return _obj
