"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr


class SuperFundProduct(BaseModel):
    """
    SuperFundProduct
    """

    abn: Optional[StrictStr] = Field(default=None, alias="ABN", description="The ABN of the Regulated SuperFund")
    usi: Optional[StrictStr] = Field(default=None, alias="USI", description="The USI of the Regulated SuperFund")
    spin: Optional[StrictStr] = Field(
        default=None,
        alias="SPIN",
        description="The SPIN of the Regulated SuperFund. This field has been deprecated. New superfunds will not have a SPIN value. The USI field should be used instead of SPIN",
    )
    product_name: Optional[StrictStr] = Field(
        default=None, alias="ProductName", description="The name of the Regulated SuperFund"
    )
    __properties = ["ABN", "USI", "SPIN", "ProductName"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SuperFundProduct:
        """Create an instance of SuperFundProduct from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SuperFundProduct:
        """Create an instance of SuperFundProduct from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SuperFundProduct.parse_obj(obj)

        _obj = SuperFundProduct.parse_obj(
            {
                "abn": obj.get("ABN"),
                "usi": obj.get("USI"),
                "spin": obj.get("SPIN"),
                "product_name": obj.get("ProductName"),
            }
        )
        return _obj
