"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

from xero_python.models.manual_tax_type import ManualTaxType


class TaxLine1(BaseModel):
    """
    TaxLine1
    """

    payslip_tax_line_id: Optional[StrictStr] = Field(
        default=None, alias="PayslipTaxLineID", description="Xero identifier for payslip tax line ID."
    )
    amount: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="Amount", description="The tax line amount"
    )
    tax_type_name: Optional[StrictStr] = Field(default=None, alias="TaxTypeName", description="Name of the tax type.")
    description: Optional[StrictStr] = Field(
        default=None, alias="Description", description="Description of the tax line."
    )
    manual_tax_type: Optional[ManualTaxType] = Field(default=None, alias="ManualTaxType")
    liability_account: Optional[StrictStr] = Field(
        default=None,
        alias="LiabilityAccount",
        description="The tax line liability account code. For posted pay run you should be able to see liability account code",
    )
    __properties = ["PayslipTaxLineID", "Amount", "TaxTypeName", "Description", "ManualTaxType", "LiabilityAccount"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaxLine1:
        """Create an instance of TaxLine1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaxLine1:
        """Create an instance of TaxLine1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaxLine1.parse_obj(obj)

        _obj = TaxLine1.parse_obj(
            {
                "payslip_tax_line_id": obj.get("PayslipTaxLineID"),
                "amount": obj.get("Amount"),
                "tax_type_name": obj.get("TaxTypeName"),
                "description": obj.get("Description"),
                "manual_tax_type": obj.get("ManualTaxType"),
                "liability_account": obj.get("LiabilityAccount"),
            }
        )
        return _obj
