"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr


class TaxComponent(BaseModel):
    """
    TaxComponent
    """

    name: Optional[StrictStr] = Field(default=None, alias="Name", description="Name of Tax Component")
    rate: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, alias="Rate", description="Tax Rate (up to 4dp)"
    )
    is_compound: Optional[StrictBool] = Field(
        default=None, alias="IsCompound", description="Boolean to describe if Tax rate is compounded."
    )
    is_non_recoverable: Optional[StrictBool] = Field(
        default=None,
        alias="IsNonRecoverable",
        description="Boolean to describe if tax rate is non-recoverable. Non-recoverable rates are only applicable to Canadian organisations",
    )
    __properties = ["Name", "Rate", "IsCompound", "IsNonRecoverable"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaxComponent:
        """Create an instance of TaxComponent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaxComponent:
        """Create an instance of TaxComponent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaxComponent.parse_obj(obj)

        _obj = TaxComponent.parse_obj(
            {
                "name": obj.get("Name"),
                "rate": obj.get("Rate"),
                "is_compound": obj.get("IsCompound"),
                "is_non_recoverable": obj.get("IsNonRecoverable"),
            }
        )
        return _obj
