"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, StrictInt, StrictStr


class TimeEntryCreateOrUpdate(BaseModel):
    """
    TimeEntryCreateOrUpdate
    """

    user_id: StrictStr = Field(
        default=..., alias="userId", description="The xero user identifier of the person logging the time."
    )
    task_id: StrictStr = Field(
        default=..., alias="taskId", description="Identifier of the task that time entry is logged against."
    )
    date_utc: datetime = Field(
        default=..., alias="dateUtc", description="Date time entry is logged on. UTC Date Time in ISO-8601 format."
    )
    duration: StrictInt = Field(
        default=..., description="Number of minutes to be logged. Duration is between 1 and 59940 inclusively."
    )
    description: Optional[StrictStr] = Field(
        default=None,
        description="An optional description of the time entry, will be set to null if not provided during update.",
    )
    __properties = ["userId", "taskId", "dateUtc", "duration", "description"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TimeEntryCreateOrUpdate:
        """Create an instance of TimeEntryCreateOrUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TimeEntryCreateOrUpdate:
        """Create an instance of TimeEntryCreateOrUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TimeEntryCreateOrUpdate.parse_obj(obj)

        _obj = TimeEntryCreateOrUpdate.parse_obj(
            {
                "user_id": obj.get("userId"),
                "task_id": obj.get("taskId"),
                "date_utc": obj.get("dateUtc"),
                "duration": obj.get("duration"),
                "description": obj.get("description"),
            }
        )
        return _obj
