"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Union

from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr


class UsageRecord(BaseModel):
    """
    UsageRecord
    """

    quantity: StrictInt = Field(default=..., description="The quantity recorded")
    subscription_id: StrictStr = Field(
        default=..., alias="subscriptionId", description="The unique identifier of the Subscription."
    )
    subscription_item_id: StrictStr = Field(
        default=..., alias="subscriptionItemId", description="The unique identifier of the SubscriptionItem."
    )
    test_mode: StrictBool = Field(
        default=..., alias="testMode", description="If the subscription is a test subscription"
    )
    recorded_at: datetime = Field(
        default=..., alias="recordedAt", description="The time when this usage was recorded in UTC"
    )
    usage_record_id: StrictStr = Field(
        default=..., alias="usageRecordId", description="The unique identifier of the usageRecord."
    )
    price_per_unit: Union[StrictFloat, StrictInt] = Field(
        default=..., alias="pricePerUnit", description="The price per unit"
    )
    product_id: StrictStr = Field(
        default=..., alias="productId", description="The unique identifier of the linked Product"
    )
    __properties = [
        "quantity",
        "subscriptionId",
        "subscriptionItemId",
        "testMode",
        "recordedAt",
        "usageRecordId",
        "pricePerUnit",
        "productId",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UsageRecord:
        """Create an instance of UsageRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UsageRecord:
        """Create an instance of UsageRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UsageRecord.parse_obj(obj)

        _obj = UsageRecord.parse_obj(
            {
                "quantity": obj.get("quantity"),
                "subscription_id": obj.get("subscriptionId"),
                "subscription_item_id": obj.get("subscriptionItemId"),
                "test_mode": obj.get("testMode"),
                "recorded_at": obj.get("recordedAt"),
                "usage_record_id": obj.get("usageRecordId"),
                "price_per_unit": obj.get("pricePerUnit"),
                "product_id": obj.get("productId"),
            }
        )
        return _obj
