"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr


class User1(BaseModel):
    """
    User1
    """

    id: StrictStr = Field(default=..., alias="Id", description="Xero identifier")
    name: Optional[StrictStr] = Field(
        default=None, alias="Name", description="Key is Name, but returns Email address of user who created the file"
    )
    first_name: Optional[StrictStr] = Field(default=None, alias="FirstName", description="First name of user")
    last_name: Optional[StrictStr] = Field(default=None, alias="LastName", description="Last name of user")
    full_name: Optional[StrictStr] = Field(default=None, alias="FullName", description="Last name of user")
    __properties = ["Id", "Name", "FirstName", "LastName", "FullName"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> User1:
        """Create an instance of User1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> User1:
        """Create an instance of User1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return User1.parse_obj(obj)

        _obj = User1.parse_obj(
            {
                "id": obj.get("Id"),
                "name": obj.get("Name"),
                "first_name": obj.get("FirstName"),
                "last_name": obj.get("LastName"),
                "full_name": obj.get("FullName"),
            }
        )
        return _obj
